/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/server/test/wire-vectors/<owner>.ts（owner = core + 声明了 C2S wire 的玩法 id）. Do not edit. */
import arenaCaptureVectors from "./arenaCapture";
import arenaDuelVectors from "./arenaDuel";
import ballMoveVectors from "./ballMove";
import coreVectors from "./core";
import idleVectors from "./idle";
import snakeVectors from "./snake";
import tallyVectors from "./tally";
import type { WireVectorFile } from "./vectorTypes";

/** owner → sidecar default（core + 声明了 C2S wire 的玩法；新增玩法只新增 wire-vectors/<id>.ts 并重跑 codegen:gameplays）。 */
export const WIRE_VECTOR_FILES: Readonly<Record<string, WireVectorFile>> = {
    arenaCapture: arenaCaptureVectors,
    arenaDuel: arenaDuelVectors,
    ballMove: ballMoveVectors,
    core: coreVectors,
    idle: idleVectors,
    snake: snakeVectors,
    tally: tallyVectors,
};
