/**
 * FairyGUI 绑定字段 codegen + 结构契约校验（纯函数，无 fairygui 运行时依赖）。类型词表用 fairygui-cc 的
 * 真实类名（`GButton`/`GTextField`/`GList`/`GLoader`/`GImage`/`GComponent`…），生成的 scaffold 可直接用。
 *
 * - `bindingFields` / `emitAutoFieldBlock`：按命名前缀约定生成 TS 绑定字段（只取有识别前缀者，普通 group 不声明）。
 * - `emitFguiViewScaffold`：生成一个 `FguiView` 子类脚手架（AUTO FIELD + `bind()` 里 `getChild<T>` + `REQUIRED` 契约）。
 * - `checkContract`：给 View 声明的必需字段，断言 `.fui` 组件是否满足（缺失/类型不符）——**结构契约无头把关**。
 * 方案见 docs/research/fairgui.md §3/§4。
 */
import type { FguiComponent, FguiElement } from "./parseFgui";

export interface BindingField {
  name: string;
  tsType: string; // fairygui-cc 类名（GButton/GTextField/...）或自定义组件类名
}

/** name 前缀 → 生成绑定字段（普通 group 等无识别前缀者不绑，与源项目 genTs.js 一致）。 */
const RECOGNIZED_PREFIXES = new Set(["btn", "txt", "ld", "lst", "img", "go", "jb"]);

/** 元素标签 → fairygui-cc 类型。component 按 name 前缀区分 GButton/自定义/GComponent。 */
const TAG_TYPE: Record<string, string> = {
  text: "GTextField", richtext: "GRichTextField", image: "GImage", loader: "GLoader",
  list: "GList", graph: "GComponent", group: "GComponent", movieclip: "GMovieClip",
};

function prefixOf(name: string): string | undefined {
  const i = name.indexOf("_");
  return i > 0 ? name.slice(0, i) : undefined;
}

/** 元素的**真实 fairygui-cc 类型**（契约比对用，能抓出"loader 却起了 lst_ 名"这类前缀/标签矛盾）。 */
export function elementTsType(el: FguiElement): string {
  if (el.tag === "component") {
    const p = prefixOf(el.name);
    if (p === "jb") { return el.fileName ? el.fileName.replace(/\.xml$/i, "") : "GComponent"; }
    if (p === "btn") { return "GButton"; }
    return "GComponent";
  }
  return TAG_TYPE[el.tag] ?? el.tag;
}

/** 元素的**绑定类型**（仅当 name 带识别前缀时才绑定；无前缀→undefined=不生成字段）。 */
export function tsTypeOf(el: FguiElement): string | undefined {
  const p = prefixOf(el.name);
  if (!p || !RECOGNIZED_PREFIXES.has(p)) { return undefined; }
  return elementTsType(el);
}

/** 生成绑定字段：只取有识别前缀的元素。 */
export function bindingFields(comp: FguiComponent): BindingField[] {
  const out: BindingField[] = [];
  for (const el of comp.elements) {
    const t = tsTypeOf(el);
    if (t) { out.push({ name: el.name, tsType: t }); }
  }
  return out;
}

/** 产出 AUTO FIELD 块（codegen 管理区，人勿手改）。 */
export function emitAutoFieldBlock(fields: BindingField[]): string {
  const lines = fields.map((f) => `  private ${f.name}!: ${f.tsType};`);
  return ["  // #region AUTO FIELD DONT CHANGE", ...lines, "  // #endregion"].join("\n");
}

export interface ScaffoldOpts {
  viewClass: string; // 生成的类名，如 OpponentHudView
  pkg: string;       // FairyGUI 包名
  comp: string;      // FairyGUI 组件名
}

/**
 * 生成一个 `FguiView` 子类脚手架：AUTO FIELD 绑定 + `bind()` 里 `getChild<T>` + `REQUIRED` 契约常量。
 * 业务逻辑（apply/onEvent）写在 AUTO 区块外。生成物放 typecheck 排除目录（依赖 fairygui-cc，Creator 侧验）。
 */
export function emitFguiViewScaffold(comp: FguiComponent, opts: ScaffoldOpts): string {
  const fields = bindingFields(comp);
  const gClasses = [...new Set(fields.map((f) => f.tsType))].filter((t) => /^G[A-Z]/.test(t)).sort();
  const importLine = gClasses.length ? `import { ${gClasses.join(", ")} } from "db://fairygui-cc/fairygui.mjs";` : "";
  const bindLines = fields.map((f) => `    this.${f.name} = this.getChild<${f.tsType}>("${f.name}");`);
  return [
    `// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://${opts.pkg}/${opts.comp}`,
    `import { FguiView } from "./FguiView";`,
    importLine,
    ``,
    `export class ${opts.viewClass} extends FguiView {`,
    `  static readonly PKG = ${JSON.stringify(opts.pkg)};`,
    `  static readonly COMP = ${JSON.stringify(opts.comp)};`,
    `  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */`,
    `  static readonly REQUIRED = ${JSON.stringify(fields)} as const;`,
    ``,
    emitAutoFieldBlock(fields),
    ``,
    `  protected bind(): void {`,
    `    // #region AUTO BIND DONT CHANGE`,
    ...bindLines,
    `    // #endregion`,
    `  }`,
    `}`,
    ``,
  ].filter((l) => l !== "").join("\n").replace(/\n\n+/g, "\n\n") + "\n";
}

export interface ContractResult {
  ok: boolean;
  missing: string[];      // View 依赖但 .fui 里没有的元素名
  mismatched: string[];   // 存在但类型不符（前缀/标签矛盾）
}

/** 结构契约校验：`.fui` 组件是否满足 View 声明的必需字段。缺失/类型不符即违约（设计师改坏 → 测试红）。 */
export function checkContract(comp: FguiComponent, required: readonly BindingField[]): ContractResult {
  const byName = new Map(comp.elements.map((e) => [e.name, e]));
  const missing: string[] = [];
  const mismatched: string[] = [];
  for (const r of required) {
    const el = byName.get(r.name);
    if (!el) { missing.push(r.name); continue; }
    const actual = elementTsType(el);
    if (actual !== r.tsType) { mismatched.push(`${r.name}: 期望 ${r.tsType}，实际 ${actual}`); }
  }
  return { ok: missing.length === 0 && mismatched.length === 0, missing, mismatched };
}
