import type { FlexNode } from '../core/flex-types.js';
import type { ResourceResolver, HostScrollSnapshot } from '../core/provider.js';
import type { EntranceOptions, HostCommand, HostBehavior, HostDriver, HostKind, HostRecord, HostValue } from '../core/host-plan.js';
import type { NestedScrollTarget } from '../core/nested-scroll.js';
import type { WebAsset } from './web-provider.js';
import { ScrollMotion } from './scroll-motion.js';
import type { SurfaceActivity, SurfacePresentationOptions, SurfaceTransitionState } from '../core/provider.js';
export interface DOMHandle {
    readonly element: HTMLElement;
    readonly flex: FlexNode;
    readonly props: Record<string, HostValue>;
    readonly disposers: Array<() => void>;
    content?: HTMLElement;
    text?: HTMLElement;
    textCanvas?: HTMLCanvasElement;
    textKey?: string;
    input?: HTMLInputElement;
    composing?: boolean;
    image?: HTMLCanvasElement;
    imageKey?: string;
    pressed?: boolean;
    rangeValue?: number;
    plainScroll?: boolean;
    scrollEnabled?: boolean;
    floatingOrder?: number;
    entrance?: {
        x: number;
        y: number;
        opacity: number;
    };
    visible: boolean;
    offset: number;
    overscroll: number;
    direction: 'vertical' | 'horizontal';
    contentMain: number;
    refresh?: () => void;
    target?: NestedScrollTarget;
    lastViewport?: string;
    animation?: number;
    motion?: ScrollMotion;
}
export declare class DOMHostDriver implements HostDriver<DOMHandle> {
    private readonly container;
    private readonly assets;
    private readonly width;
    private readonly height;
    private readonly anchorsChanged;
    private readonly scrollChanged;
    readonly metrics: {
        dirtyRoots: number;
        measuredLeaves: number;
        percentageFallbacks: number;
        layoutPasses: number;
        layoutMs: number;
        writebackMs: number;
    };
    private readonly records;
    private readonly created;
    private readonly callbacks;
    private readonly nested;
    private readonly glyphs;
    private root;
    private dirty;
    private readonly paint;
    private frame;
    private animation;
    private readonly activeMotions;
    private disposed;
    private suppressClick;
    private clickReset;
    private consumeClick;
    private consumeClickReset;
    private pressedButton?;
    private pointerMove?;
    private pointerEnd?;
    private surfaceActivity;
    private cancelSurfaceTransition?;
    private readonly onPointerMove;
    private readonly onPointerEnd;
    private readonly onClickCapture;
    private readonly window;
    private readonly interactionStyle;
    private readonly presentation;
    private floatingSequence;
    constructor(container: HTMLElement, assets: ResourceResolver<WebAsset>, width: number, height: number, anchorsChanged?: () => void, scrollChanged?: ((scroll: HostScrollSnapshot) => void) | undefined);
    private readonly onResize;
    create(kind: HostKind, planId: number, behavior?: HostBehavior): DOMHandle;
    private imageCanvas;
    inspect(): import("../core/provider.js").InspectedNode[];
    paintSnapshot(context: CanvasRenderingContext2D): void;
    present(activity: SurfaceActivity, order: number, options: SurfacePresentationOptions, transitionState: SurfaceTransitionState): void | Promise<void>;
    private fadeSurface;
    validate(commands: readonly HostCommand<DOMHandle>[]): void;
    commit(commands: readonly HostCommand<DOMHandle>[]): void;
    scheduleFlush(callback: () => void): void;
    scheduleDelayed(callback: () => void, delayMs: number): () => void;
    startEntrance(record: HostRecord<DOMHandle>, options: EntranceOptions, complete: () => void): () => void;
    private writePresentation;
    flushLayout(): void;
    private layoutFloatingPanels;
    flushVirtualLayout(record: HostRecord<DOMHandle>): void;
    findAnchor(name: string): {
        width: number;
        height: number;
        x: number;
        y: number;
    } | undefined;
    private isRecordVisible;
    readVirtualViewport(record: HostRecord<DOMHandle>, direction: 'vertical' | 'horizontal'): {
        offset: number;
        mainSize: number;
        crossSize: number;
        scrolling: boolean;
    };
    scrollVirtualTo(record: HostRecord<DOMHandle>, _direction: 'vertical' | 'horizontal', offset: number, duration: number): void;
    stopVirtualScroll(record: HostRecord<DOMHandle>): void;
    destroy(): void;
    private releasePressedButton;
    private property;
    private write;
    private writeInput;
    private writeText;
    private writeImage;
    private writeRange;
    private paintImage;
    private writePlainScroll;
    private writeFloating;
    private floatingPanel;
    private floatingAnchorRecord;
    private floatingAnchorRect;
    private topFloating;
    private refreshFloatings;
    private globalRect;
    private hideDetachedDescendants;
    private writeVirtual;
    private writeOffset;
    private setOffset;
    private writeMotion;
    private notifyScroll;
    private target;
    private interruptInitial;
    private bindInput;
    private animate;
}
