/** AUTO-GENERATED by apps/server/tools/plugin-codegen/cli.ts from apps/kits/<id>/kit.json. Do not edit. */
import { type KitCatalogEntry, type KitEffectSpec } from "./catalogTypes";

/** 已登记 kit（按 id 排序）。 */
export const KIT_CATALOG: readonly KitCatalogEntry[] = [];

/** `kit:<kitId>:<name>` → effect 规格（economy.ts validateGrant 与 Lua 镜像的共同真源）。 */
export const KIT_EFFECT_KINDS: Readonly<Record<string, KitEffectSpec>> = {};
