/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json} + apps/plugins/<id>/gameplay/{manifest.json,state.json}. Do not edit. */
import { WireValidationError } from "../protocol/http";
import { validateArenaCaptureRoomState, type IArenaCaptureRoomState } from "./generated/state/arenaCapture";
import { validateArenaDuelRoomState, type IArenaDuelRoomState } from "./generated/state/arenaDuel";
import { validateGameRoomState, type IGameRoomState } from "./generated/state/ballMove";
import { validateDropInFixtureState, type IDropInFixtureState } from "./generated/state/dropInFixture";
import { validateIdleRoomState, type IIdleRoomState } from "./generated/state/idle";
import { validateMmoWorldRoomState, type IMmoWorldRoomState } from "./generated/state/mmoWorld";
import { validatePrivateFixtureState, type IPrivateFixtureState } from "./generated/state/privateFixture";
import { validateSnakeRoomState, type ISnakeRoomState } from "./generated/state/snake";
import { validateTallyRoomState, type ITallyRoomState } from "./generated/state/tally";
import { validateViewFixtureState, type IViewFixtureState } from "./generated/state/viewFixture";
import { validateWorldFixtureState, type IWorldFixtureState } from "./generated/state/worldFixture";

/** Wire root interfaces keyed by canonical gameplay mode id. */
export interface RoomStateByMode {
    "arenaCapture": IArenaCaptureRoomState;
    "arenaDuel": IArenaDuelRoomState;
    "ballMove": IGameRoomState;
    "dropInFixture": IDropInFixtureState;
    "idle": IIdleRoomState;
    "mmoWorld": IMmoWorldRoomState;
    "privateFixture": IPrivateFixtureState;
    "snake": ISnakeRoomState;
    "tally": ITallyRoomState;
    "viewFixture": IViewFixtureState;
    "worldFixture": IWorldFixtureState;
}

export type RoomStateMode = keyof RoomStateByMode;
export type RoomState = RoomStateByMode[RoomStateMode];
export type RoomStateValidator<M extends RoomStateMode> = (input: unknown) => RoomStateByMode[M];

export const ROOM_STATE_VALIDATORS = Object.freeze({
    "arenaCapture": validateArenaCaptureRoomState,
    "arenaDuel": validateArenaDuelRoomState,
    "ballMove": validateGameRoomState,
    "dropInFixture": validateDropInFixtureState,
    "idle": validateIdleRoomState,
    "mmoWorld": validateMmoWorldRoomState,
    "privateFixture": validatePrivateFixtureState,
    "snake": validateSnakeRoomState,
    "tally": validateTallyRoomState,
    "viewFixture": validateViewFixtureState,
    "worldFixture": validateWorldFixtureState,
} as const satisfies { readonly [M in RoomStateMode]: RoomStateValidator<M> });

export function validateRoomStateForMode<M extends RoomStateMode>(mode: M, input: unknown): RoomStateByMode[M];
export function validateRoomStateForMode(mode: string, input: unknown): RoomState;
export function validateRoomStateForMode(mode: string, input: unknown): RoomState {
    const validator = (ROOM_STATE_VALIDATORS as Readonly<Partial<Record<string, (value: unknown) => RoomState>>>)[mode];
    if (!validator) throw new WireValidationError("STATE_MODE", "mode");
    return validator(input);
}

/** Per-gameplay catalog. contractDigest = sha256(manifest.json + "\0" + state.json + "\0" + wire.ts). */
export const GAMEPLAY_CATALOG = {
    "arenaCapture": {
        id: "arenaCapture",
        constantName: "ArenaCapture",
        modeVersion: 1,
        maxPlayers: 4,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "25e5743ce57bb9476c010fd9f16f294e824d965723b1474b0c2c4ef905594073",
    },
    "arenaDuel": {
        id: "arenaDuel",
        constantName: "ArenaDuel",
        modeVersion: 1,
        maxPlayers: 2,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "3215ad969e1b6aeab48af2ddc26f0db2b51ab793b6db244c15b1390746a8e203",
    },
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 3,
        maxPlayers: 4,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "c8fca655408e3bae34c9b3072681536e03b9258bdc97d827015ccf19feea677e",
    },
    "dropInFixture": {
        id: "dropInFixture",
        constantName: "DropInFixture",
        modeVersion: 2,
        maxPlayers: 8,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "af9fcc0be748fbed155af39397601af6a6364a5994eb9ac90dbb1d0d02dbb2fb",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 3,
        maxPlayers: 4,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "0ecdaaa95a97d83b73df2a3f3d5535f0e4bf113fb50fa64c52a79477f0749ef7",
    },
    "mmoWorld": {
        id: "mmoWorld",
        constantName: "MmoWorld",
        modeVersion: 5,
        maxPlayers: 100,
        roster: "hidden",
        kind: "world",
        world: {"emptyPolicy":"sleep","emptyAfterMs":120000,"checkpointMs":30000},
        profiles: ["world"],
        stateFragments: [],
        contractDigest: "6388fa9f3519dc78a4dba00232fa4c0b999bbe7c1cbb4fb078cf95400781fc39",
    },
    "privateFixture": {
        id: "privateFixture",
        constantName: "PrivateFixture",
        modeVersion: 2,
        maxPlayers: 4,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["default", "private"],
        stateFragments: ["ownerReady", "inviteRoom"],
        contractDigest: "d1df12c9dcfdbecd1ff5f6363876335efae1bb4a75c2123d037a4319d6130c8d",
    },
    "snake": {
        id: "snake",
        constantName: "Snake",
        modeVersion: 5,
        maxPlayers: 8,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "0da0f2bcef6b3e344d5e3feff358f08755a80280364ae57ef5126e9d6ec25e33",
    },
    "tally": {
        id: "tally",
        constantName: "Tally",
        modeVersion: 1,
        maxPlayers: 4,
        roster: "public",
        kind: "match",
        world: null,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "7ad4475966b16783bd73ab6dff8925d5b6e3c010236ff2ceba8c08792f66bc1b",
    },
    "viewFixture": {
        id: "viewFixture",
        constantName: "ViewFixture",
        modeVersion: 2,
        maxPlayers: 8,
        roster: "hidden",
        kind: "match",
        world: null,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "14ea5e8a263303a47181669dab9fbaf2769c63ffe9de1d4712ac2f887ec3bf3f",
    },
    "worldFixture": {
        id: "worldFixture",
        constantName: "WorldFixture",
        modeVersion: 3,
        maxPlayers: 8,
        roster: "hidden",
        kind: "world",
        world: {"emptyPolicy":"sleep","emptyAfterMs":120000,"checkpointMs":30000},
        profiles: ["world"],
        stateFragments: [],
        contractDigest: "d23b50c9735af39cc58ac7e9db9bbf9e23a1317b2a6a02382a4e1814324f81c1",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;
