/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json}. Do not edit. */
// 稳定 façade：外部只 import 本文件或包根 barrel，⛔ 不直接 import generated/ 内部路径。
export * from "./catalog.generated";
export * from "./generated/state/ballMove";
export * from "./generated/state/idle";
