/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json} + apps/plugins/<id>/gameplay/{manifest.json,state.json}. Do not edit. */
// 稳定 façade：外部只 import 本文件或包根 barrel，⛔ 不直接 import generated/ 内部路径。
export * from "./defineGameplayWire";
export * from "./catalog.generated";
export * from "./generated/wire-catalog.generated";
export * from "./arenaCapture/wire";
export * from "./generated/state/arenaCapture";
export * from "./arenaDuel/wire";
export * from "./generated/state/arenaDuel";
export * from "./ballMove/wire";
export * from "./ballMove/roster";
export * from "./generated/state/ballMove";
export * from "./generated/state/dropInFixture";
export * from "./idle/wire";
export * from "./generated/state/idle";
export * from "./generated/state/privateFixture";
export * from "./snake/ruleset";
export * from "./snake/wire";
export * from "./snake/cosmetics";
export * from "./snake/progression";
export * from "./snake/snakeSkinCatalogData";
export * from "./generated/state/snake";
export * from "./tally/wire";
export * from "./generated/state/tally";
