// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://View_Home_Home/Home
import { FguiView } from "./FguiView";
import { HomeLogic } from "../logic/page/HomeLogic";
// #region AUTO IMPORT DONT CHANGE
import { GButton, GTextField } from "db://fairygui-cc/fairygui.mjs";
// #endregion AUTO IMPORT

export class HomeView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "View_Home_Home";
  static readonly COMP = "Home";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [{"name":"txt_userId","tsType":"GTextField"},{"name":"btn_enter","tsType":"GButton"}] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  protected txt_userId!: GTextField;
  protected btn_enter!: GButton;
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    this.txt_userId = this.getChild<GTextField>("txt_userId");
    this.btn_enter = this.getChild<GButton>("btn_enter");
    // #endregion AUTO BIND
  }

  // ── 业务（AUTO 区块外，Creator 侧验证）────────────────────────
  /** 「进入游戏」回调（Main 注入：退大厅壳、进 ballMove 玩法房）。 */
  onEnterBattle: () => void | Promise<void> = () => {};
  private logic: HomeLogic | null = null;
  private setupWired = false;

  private readonly handleEnter = (): void => {
    this.observeAsync(() => this.logic?.enterBattle(), "enter-battle");
  };

  /** 渲染 + 接线（opener 调用）：展示用户 id，按钮走 HomeLogic → onEnterBattle。 */
  setup(uid: string): void {
    this.txt_userId.text = uid;
    if (!this.logic) this.logic = new HomeLogic();
    this.logic.setUserId(uid);
    this.logic.onEnterBattle = () => this.onEnterBattle();
    if (!this.setupWired) {
      this.setupWired = true;
      this.btn_enter.onClick(this.handleEnter, this);
    }
  }
}
