// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://View_Home_Home/Home
import { FguiView } from "./FguiView";
import { HomeLogic, type HomeMenuEntryModel } from "../logic/page/HomeLogic";
// #region AUTO IMPORT DONT CHANGE
import { GButton, GTextField } from "db://fairygui-cc/fairygui.mjs";
// #endregion AUTO IMPORT

export class HomeView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "View_Home_Home";
  static readonly COMP = "Home";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [{"name":"txt_userId","tsType":"GTextField"},{"name":"btn_enter","tsType":"GButton"}] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  protected txt_userId!: GTextField;
  protected btn_enter!: GButton;
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    this.txt_userId = this.getChild<GTextField>("txt_userId");
    this.btn_enter = this.getChild<GButton>("btn_enter");
    // #endregion AUTO BIND
  }

  // ── 业务（AUTO 区块外，Creator 侧验证）────────────────────────
  /** 「进入游戏」回调（无菜单入口数据时的回退通道，opener 注入）。 */
  onEnterBattle: () => void | Promise<void> = () => {};
  private logic: HomeLogic | null = null;
  private setupWired = false;

  private readonly handleEnter = (): void => {
    this.observeAsync(() => this.logic?.enterBattle(), "enter-battle");
  };

  /**
   * 渲染 + 接线（opener 调用）：展示用户 id；入口数据来自 generated menu
   * contributions（§7.4）——contribution[0] 的标题渲染到现 btn_enter，点击经
   * HomeLogic 统一走 entry.launch（生产接线 LaunchPort.launch）。
   * ⚠ Home 视觉仍是单按钮（FGUI 编辑器不可用）：多入口只渲染第一条并 warn，
   * 「玩法入口列表 GList」是编辑器待办项。
   */
  setup(uid: string, entries?: readonly HomeMenuEntryModel[]): void {
    this.txt_userId.text = uid;
    if (!this.logic) this.logic = new HomeLogic();
    this.logic.setUserId(uid);
    this.logic.onEnterBattle = () => this.onEnterBattle();
    if (entries) {
      this.logic.setEntries(entries);
      const primary = entries[0];
      if (primary) {
        this.btn_enter.title = primary.label;
        // disabled/failed 叠加：不可点击占位（§7.4——绝不显示必然失败的正常入口）。
        this.btn_enter.grayed = !primary.enabled;
        this.btn_enter.touchable = primary.enabled;
      }
      if (entries.length > 1) {
        console.warn(`[HomeView] ${entries.length} 条菜单入口但视觉仍是单按钮：仅渲染 contribution[0]（入口列表 GList 为 FGUI 编辑器待办）`);
      }
    }
    if (!this.setupWired) {
      this.setupWired = true;
      this.btn_enter.onClick(this.handleEnter, this);
    }
  }
}
