// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://View_AreaList_Login/Login
import { FguiView } from "./FguiView";
import type { WebPlatformAreaServer } from "../shared/index";
import { areaStatusIconUrl } from "./areaPresentation";
// #region AUTO IMPORT DONT CHANGE
import { GButton, GComponent, GGroup, GLoader, GLoader3D, GProgressBar, GRichTextField, GTextField } from "db://fairygui-cc/fairygui.mjs";
// #endregion AUTO IMPORT

export class LoginView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "View_AreaList_Login";
  static readonly COMP = "Login";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [{"name":"ld_logo","tsType":"GLoader"},{"name":"btn_copy","tsType":"GButton"},{"name":"btn_ageTip","tsType":"GButton"},{"name":"btn_musicon","tsType":"GButton"},{"name":"btn_musicoff","tsType":"GButton"},{"name":"btn_notice","tsType":"GButton"},{"name":"btn_account","tsType":"GButton"},{"name":"go_topBtns","tsType":"GGroup"},{"name":"go_top","tsType":"GGroup"},{"name":"txt_progress","tsType":"GTextField"},{"name":"pg_loading","tsType":"GProgressBar"},{"name":"go_bottom","tsType":"GGroup"},{"name":"go_container","tsType":"GComponent"},{"name":"txt_privacy","tsType":"GRichTextField"},{"name":"btn_select","tsType":"GButton"},{"name":"ld3_testAnim","tsType":"GLoader3D"},{"name":"btn_login","tsType":"GButton"},{"name":"btn_server","tsType":"GButton"},{"name":"btn_test","tsType":"GButton"},{"name":"btn_clearDataCache","tsType":"GButton"}] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  protected ld_logo!: GLoader;
  protected btn_copy!: GButton;
  protected btn_ageTip!: GButton;
  protected btn_musicon!: GButton;
  protected btn_musicoff!: GButton;
  protected btn_notice!: GButton;
  protected btn_account!: GButton;
  protected go_topBtns!: GGroup;
  protected go_top!: GGroup;
  protected txt_progress!: GTextField;
  protected pg_loading!: GProgressBar;
  protected go_bottom!: GGroup;
  protected go_container!: GComponent;
  protected txt_privacy!: GRichTextField;
  protected btn_select!: GButton;
  protected ld3_testAnim!: GLoader3D;
  protected btn_login!: GButton;
  protected btn_server!: GButton;
  protected btn_test!: GButton;
  protected btn_clearDataCache!: GButton;
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    this.ld_logo = this.getChild<GLoader>("ld_logo");
    this.btn_copy = this.getChild<GButton>("btn_copy");
    this.btn_ageTip = this.getChild<GButton>("btn_ageTip");
    this.btn_musicon = this.getChild<GButton>("btn_musicon");
    this.btn_musicoff = this.getChild<GButton>("btn_musicoff");
    this.btn_notice = this.getChild<GButton>("btn_notice");
    this.btn_account = this.getChild<GButton>("btn_account");
    this.go_topBtns = this.getChild<GGroup>("go_topBtns");
    this.go_top = this.getChild<GGroup>("go_top");
    this.txt_progress = this.getChild<GTextField>("txt_progress");
    this.pg_loading = this.getChild<GProgressBar>("pg_loading");
    this.go_bottom = this.getChild<GGroup>("go_bottom");
    this.go_container = this.getChild<GComponent>("go_container");
    this.txt_privacy = this.getChild<GRichTextField>("txt_privacy");
    this.btn_select = this.getChild<GButton>("btn_select");
    this.ld3_testAnim = this.getChild<GLoader3D>("ld3_testAnim");
    this.btn_login = this.getChild<GButton>("btn_login");
    this.btn_server = this.getChild<GButton>("btn_server");
    this.btn_test = this.getChild<GButton>("btn_test");
    this.btn_clearDataCache = this.getChild<GButton>("btn_clearDataCache");
    // #endregion AUTO BIND
  }

  // ── 业务（AUTO 区块外，Creator 侧验证）────────────────────────
  /** 「进入游戏」按钮回调（opener 注入：登录 → 打开选服/主界面） */
  onEnter: () => void | Promise<void> = () => {};
  /** 「公告」按钮回调（opener 注入：打开公告页） */
  onNotice: () => void | Promise<void> = () => {};
  /** 「选服」按钮回调（opener 注入：打开选服列表） */
  onSelectServer: () => void | Promise<void> = () => {};
  private setupWired = false;

  /** 事件系统不会等待 Promise；这些稳定 wrapper 让重复 setup 只注册一次且观察 rejection。 */
  private readonly handleEnter = (): void => { this.observeAsync(() => this.onEnter(), "login"); };
  private readonly handleNotice = (): void => { this.observeAsync(() => this.onNotice(), "notice"); };
  private readonly handleSelectServer = (): void => {
    this.observeAsync(() => this.onSelectServer(), "select-server");
  };

  /** 接线（opener 调用）：把主要按钮连到注入回调；进度条走 setProgress。 */
  setup(): void {
    // ld_logo 在 .fui 里 clearOnPublish（原项目按语言包换图设计），发布产物 url 为空——
    // 必须代码装载。图在 L10n_zh_hans 包（本页 sharedPkgs 已预加载；跨包写错包名不报错、
    // 运行时空白，靠 viewRegistry.test 的「代码内 ui:// ⊆ 闭包」机检把关）。
    this.ld_logo.url = "ui://L10n_zh_hans/login_logo";
    if (!this.setupWired) {
      this.setupWired = true;
      this.btn_login.onClick(this.handleEnter, this);
      this.btn_notice.onClick(this.handleNotice, this);
      // btn_select / btn_server 都指向选服（源项目历史遗留双入口）
      this.btn_select.onClick(this.handleSelectServer, this);
      this.btn_server.onClick(this.handleSelectServer, this);
      this.markUnusedControlsAsPlaceholders();
    }
  }

  /** 显示当前选中区服（Public API 字符串 status 映射到现有 login_status_{1|2|9} 资源）。 */
  showCurrentServer(server: Pick<WebPlatformAreaServer, "name" | "status"> | null): void {
    this.btn_server.title = server ? server.name : "未开服";
    // 状态图标在 Dynamic_Login 包（⛔ 不是本页包——写错包名不报错、运行时图标空白，
    // viewRegistry.test 的「代码内 ui:// 引用 ⊆ 闭包」扫描把关）
    if (server) { this.btn_server.icon = areaStatusIconUrl(server.status); }
  }

  /** 登录进度（0~1 + 文案）——LoginLogic.onProgress 回调驱动。 */
  setProgress(ratio: number, text: string): void {
    const bounded = Number.isFinite(ratio) ? Math.max(0, Math.min(1, ratio)) : 0;
    const min = Number.isFinite(this.pg_loading.min) ? this.pg_loading.min : 0;
    const max = Number.isFinite(this.pg_loading.max) && this.pg_loading.max > min
      ? this.pg_loading.max : 100;
    this.pg_loading.value = min + bounded * (max - min);
    this.txt_progress.text = text;
  }

  /**
   * Login 设计仍保留一批渠道/调试控件，但本仓当前没有对应业务能力。
   * 明确标成展示占位，避免 required contract 被误读为「已有可用接线」。
   */
  private markUnusedControlsAsPlaceholders(): void {
    for (const button of [
      this.btn_copy, this.btn_ageTip, this.btn_musicon, this.btn_musicoff,
      this.btn_account, this.btn_test, this.btn_clearDataCache,
    ]) {
      button.touchable = false;
      button.grayed = true;
    }
    this.ld3_testAnim.visible = false;
    // txt_privacy 与 ld_logo 是纯展示元素，保留可见但不伪造交互能力。
  }
}
