// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://Common_Component/GoContainer
import { FguiView } from "./FguiView";
import { GComponent, GTextField } from "db://fairygui-cc/fairygui.mjs";
import { Color } from "cc";
import { DEV } from "cc/env";
import { spikeSession } from "./scene3d/spikeSession";
import { ViewMgr, type ViewHandle } from "./ViewMgr";
import type { ViewLifecycleContext } from "./ViewBase";
import { ConfirmLogic } from "../logic/page/ConfirmLogic";
import type { ConfirmView } from "./ConfirmView";
// #region AUTO IMPORT DONT CHANGE
// #endregion AUTO IMPORT

export class Stage3dSpikeHudView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "Common_Component";
  static readonly COMP = "GoContainer";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    // #endregion AUTO BIND
  }

  private readonly modals = new Set<ViewHandle>();

  protected onOpen(context: ViewLifecycleContext): void {
    if (!DEV) throw new Error("SC0 HUD is only available in development");
    this.root.opaque = false;
    const counter = this.button("Stage3dSpike.HudButton", "HUD 0", 24, 48, () => {
      counter.text = `HUD ${++spikeSession.logic.hudClicks}`;
    });
    this.button("Stage3dSpike.ModalButton", "打开模态", 224, 48, () => {
      this.observeAsync(async () => {
        const logic = new ConfirmLogic({ title: "SC0 输入取消", content: "关闭后须重新按下；旧拖拽与加速不得恢复。", noText: null });
        const handle = await ViewMgr.open("Confirm");
        if (!context.isActive()) { handle.close(); return; }
        this.modals.add(handle);
        logic.onClose = () => { this.modals.delete(handle); handle.close(); };
        try { await handle.run((view) => (view as ConfirmView).setup(logic)); }
        catch (error) {
          const stillOwned = this.modals.delete(handle);
          if (stillOwned) handle.close();
          // Confirm may be clicked while UniFlex is still committing its first
          // frame. Our close then cancels goto.ready; only that owned shutdown
          // is expected. Setup failures and unsolicited cancellations still fail.
          if (!stillOwned && isDestroyedNavigationCancellation(error)) return;
          throw error;
        }
      }, "sc0-modal");
    });
    this.button("Stage3dSpike.CloseButton", "关闭夹具", 424, 48, () => spikeSession.close());
  }

  private button(name: string, text: string, x: number, y: number, click: () => void): GTextField {
    const button = new GComponent();
    button.name = name;
    button.node.name = name;
    button.opaque = true;
    button.x = x; button.y = y;
    button.setSize(180, 84);
    this.root.addChild(button);
    const label = new GTextField();
    label.name = "label";
    label.text = text;
    label.width = 180; label.height = 84;
    label.fontSize = 30;
    label.color = new Color(255, 220, 96, 255);
    label.touchable = false;
    button.addChild(label);
    button.onClick(click, this);
    return label;
  }

  protected onCloseLifecycle(): void {
    for (const handle of this.modals) handle.close();
    this.modals.clear();
  }
}

function isDestroyedNavigationCancellation(error: unknown): boolean {
  // The locked UniFlex runtime does not export its cancellation class as a value.
  return error instanceof Error
    && error.name === "NavigationCancelledError"
    && error.message === "Navigation was cancelled: destroyed"
    && (error as Error & { reason?: unknown }).reason === "destroyed";
}
