/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json} + apps/plugins/<id>/gameplay/{manifest.json,state.json} + apps/client/src/gameplay/modes/<id>/index.ts. Do not edit. */
import { registerGameplayModule } from "../logic/gameplay/GameplayModule";
import type { AppGameplayRegistry, GameplayServicesContext } from "./services";
import { createGameplayModule as createBallMoveGameplayModule } from "./modes/ballMove/index";
import { createGameplayModule as createIdleGameplayModule } from "./modes/idle/index";
import { createGameplayModule as createSnakeGameplayModule } from "./modes/snake/index";
import { createGameplayModule as createTallyGameplayModule } from "./modes/tally/index";

/** Per-gameplay catalog mirror. contractDigest = sha256(manifest.json + "\0" + state.json + "\0" + wire.ts). */
export const GAMEPLAY_CATALOG = {
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "c8fca655408e3bae34c9b3072681536e03b9258bdc97d827015ccf19feea677e",
    },
    "dropInFixture": {
        id: "dropInFixture",
        constantName: "DropInFixture",
        modeVersion: 2,
        maxPlayers: 8,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "af9fcc0be748fbed155af39397601af6a6364a5994eb9ac90dbb1d0d02dbb2fb",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "0ecdaaa95a97d83b73df2a3f3d5535f0e4bf113fb50fa64c52a79477f0749ef7",
    },
    "privateFixture": {
        id: "privateFixture",
        constantName: "PrivateFixture",
        modeVersion: 2,
        maxPlayers: 4,
        profiles: ["default", "private"],
        stateFragments: ["ownerReady", "inviteRoom"],
        contractDigest: "d1df12c9dcfdbecd1ff5f6363876335efae1bb4a75c2123d037a4319d6130c8d",
    },
    "snake": {
        id: "snake",
        constantName: "Snake",
        modeVersion: 5,
        maxPlayers: 8,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "0da0f2bcef6b3e344d5e3feff358f08755a80280364ae57ef5126e9d6ec25e33",
    },
    "tally": {
        id: "tally",
        constantName: "Tally",
        modeVersion: 1,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "7ad4475966b16783bd73ab6dff8925d5b6e3c010236ff2ceba8c08792f66bc1b",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;

/** 已装配客户端 module 的玩法（canonical GameplayModeId ∩ catalog；fixture 玩法不在此表）。 */
export const GAMEPLAY_MODULES = {
    "ballMove": createBallMoveGameplayModule,
    "idle": createIdleGameplayModule,
    "snake": createSnakeGameplayModule,
    "tally": createTallyGameplayModule,
} as const;

export type GameplayModuleId = keyof typeof GAMEPLAY_MODULES;

/**
 * 登记全部 generated gameplay module（§7.6）：每个 module 只注入稳定服务，
 * 后续登记失败回滚本次已登记项（逆序），⛔ 不影响调用前已有登记。
 */
export function registerGeneratedGameplays(
    registry: AppGameplayRegistry,
    services: GameplayServicesContext,
): () => void {
    const disposers: Array<() => void> = [];
    try {
        disposers.push(registerGameplayModule(registry, createBallMoveGameplayModule(services), services.controllerBridge));
        disposers.push(registerGameplayModule(registry, createIdleGameplayModule(services), services.controllerBridge));
        disposers.push(registerGameplayModule(registry, createSnakeGameplayModule(services), services.controllerBridge));
        disposers.push(registerGameplayModule(registry, createTallyGameplayModule(services), services.controllerBridge));
    } catch (error) {
        for (const dispose of disposers.splice(0).reverse()) dispose();
        throw error;
    }
    return () => {
        for (const dispose of disposers.splice(0).reverse()) dispose();
    };
}
