/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json}. Do not edit. */

/** Per-gameplay catalog mirror (minimal; extended in stage 9). contractDigest = sha256(manifest.json + "\0" + state.json). */
export const GAMEPLAY_CATALOG = {
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 1,
        maxPlayers: 4,
        contractDigest: "b2dbbf2589da1f554fccfcaea0b9e0167f664744c2bca310f7be72705278884b",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 1,
        maxPlayers: 4,
        contractDigest: "ebb621e7aa80ab74098763725f4931a009dba144900a69dccd69bdb2485fce77",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;
