// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://View_AreaList_AreaList/AreaList
import { FguiView } from "./FguiView";
import { Event, GComponent, GObject } from "db://fairygui-cc/fairygui.mjs";
import type { AreaListLogic, AreaTab } from "../logic/page/AreaListLogic";
import type { IAreaServer } from "../shared/index";
// #region AUTO IMPORT DONT CHANGE
import { GButton, GList, GLoader, GTextField } from "db://fairygui-cc/fairygui.mjs";
// #endregion AUTO IMPORT

export class AreaListView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "View_AreaList_AreaList";
  static readonly COMP = "AreaList";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [{"name":"btn_mask","tsType":"GButton"},{"name":"lst_server","tsType":"GList"},{"name":"lst_my","tsType":"GList"},{"name":"jb_tabbar","tsType":"GList"},{"name":"ld_status2","tsType":"GLoader"},{"name":"ld_status1","tsType":"GLoader"},{"name":"ld_status9","tsType":"GLoader"},{"name":"txt_title","tsType":"GTextField"},{"name":"btn_close","tsType":"GButton"}] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  private btn_mask!: GButton;
  private lst_server!: GList;
  private lst_my!: GList;
  private jb_tabbar!: GList;
  private ld_status2!: GLoader;
  private ld_status1!: GLoader;
  private ld_status9!: GLoader;
  private txt_title!: GTextField;
  private btn_close!: GButton;
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    this.btn_mask = this.getChild<GButton>("btn_mask");
    this.lst_server = this.getChild<GList>("lst_server");
    this.lst_my = this.getChild<GList>("lst_my");
    this.jb_tabbar = this.getChild<GList>("jb_tabbar");
    this.ld_status2 = this.getChild<GLoader>("ld_status2");
    this.ld_status1 = this.getChild<GLoader>("ld_status1");
    this.ld_status9 = this.getChild<GLoader>("ld_status9");
    this.txt_title = this.getChild<GTextField>("txt_title");
    this.btn_close = this.getChild<GButton>("btn_close");
    // #endregion AUTO BIND
  }

  // ── 业务（AUTO 区块外，Creator 侧验证）────────────────────────
  private servers: IAreaServer[] = [];
  private tabs: { key: AreaTab; title: string }[] = [];
  private selectedTabIndex = -1;

  /** 「关闭」按钮或遮罩回调（opener 注入：关闭选服面板不选服）。 */
  onClose: () => void = () => {};

  /** 接线 AreaListLogic：固定页签 + 虚拟列表；点区服走 logic.choose；按钮或遮罩关闭走 onClose。 */
  setup(logic: AreaListLogic): void {
    logic.onTabs = (tabs) => this.renderTabs(tabs, logic.currentTab);
    logic.onServers = (servers) => this.renderServers(servers);
    this.btn_mask.onClick(() => this.onClose(), this);
    this.btn_close.onClick(() => this.onClose(), this);
    // 页签 jb_tabbar（本包内 GList）：点项切换推荐/我的角色/全部区服
    // ⚠ fairygui-cc 注册项点击用 on(Event.CLICK_ITEM,...)；onClickItem 是内部处理器（直接调会 GObject.cast(undefined) 崩）
    this.jb_tabbar.on(Event.CLICK_ITEM, (item: GObject) => {
      const idx = this.jb_tabbar.getChildIndex(item);
      const tab = this.tabs[idx];
      if (tab) {
        logic.setTab(tab.key);
        this.selectTab(idx);
      }
    }, this);
    // 区服虚拟列表：itemRenderer 填每项 AreaItem，点项 choose
    this.lst_server.setVirtual();
    this.lst_server.itemRenderer = (idx, obj) => this.renderItem(idx, obj as GComponent);
    this.lst_server.on(Event.CLICK_ITEM, (obj: GObject) => {
      // 虚拟列表：点击给的是渲染子对象，需转成逻辑项索引（滚动后子索引≠项索引）
      const idx = this.lst_server.childIndexToItemIndex(this.lst_server.getChildIndex(obj));
      const s = this.servers[idx];
      if (s) logic.choose(s.sId);
    }, this);
  }

  private renderTabs(tabs: { key: AreaTab; title: string }[], selected: AreaTab): void {
    this.tabs = tabs;
    this.selectedTabIndex = tabs.findIndex((tab) => tab.key === selected);
    this.jb_tabbar.itemRenderer = (idx, obj) => {
      const item = obj as GComponent;
      const title = tabs[idx]?.title ?? "";
      item.getChild<GTextField>("txt_title1").text = title;
      item.getChild<GTextField>("txt_title2").text = title;
      this.applyTabState(item, idx === this.selectedTabIndex);
    };
    this.jb_tabbar.numItems = tabs.length;
    this.selectTab(this.selectedTabIndex);
  }

  private selectTab(index: number): void {
    if (index < 0) return;
    this.selectedTabIndex = index;
    for (let i = 0; i < this.jb_tabbar.numChildren; i++) {
      this.applyTabState(this.jb_tabbar.getChildAt(i).asCom, i === index);
    }
  }

  private applyTabState(item: GComponent, selected: boolean): void {
    const controller = item.getController("lib");
    if (controller) controller.selectedIndex = selected ? 1 : 0;
    const open = item.getChild("go_open"); if (open) open.visible = selected;
    const close = item.getChild("go_close"); if (close) close.visible = !selected;
  }

  private renderServers(servers: IAreaServer[]): void {
    this.servers = servers;
    this.lst_server.numItems = servers.length;
  }

  private renderItem(idx: number, item: GComponent): void {
    const s = this.servers[idx];
    if (!s) return;
    // ⚠ 本 fairygui-cc 版只有 .asCom，无 .asTextField/.asLoader —— 用 getChild<T>(泛型)取类型化子项
    item.getChild<GTextField>("txt_serverName").text = s.name;
    item.getChild("go_new").visible = s.t === 1;    // 新服角标
    item.getChild("go_full").visible = s.t === 2;   // 爆满角标
    item.getChild<GLoader>("ld_status").url = `ui://View_AreaList_AreaList/login_status_${s.status}`;
    const openTime = item.getChild<GTextField>("txt_openTime");
    openTime.visible = s.openTime > 0;
    if (s.openTime > 0) {
      openTime.text = new Date(s.openTime * 1000).toLocaleDateString();
    }
  }
}
