// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://View_SharedWidget_Confirm/Confirm
import { FguiView } from "./FguiView";
import { GButton, GRichTextField, GTextField } from "db://fairygui-cc/fairygui.mjs";
import type { ConfirmLogic } from "../logic/page/ConfirmLogic";
// #region AUTO IMPORT DONT CHANGE
import { GGroup } from "db://fairygui-cc/fairygui.mjs";
// #endregion AUTO IMPORT

export class ConfirmView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "View_SharedWidget_Confirm";
  static readonly COMP = "Confirm";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [{"name":"go_noBtn","tsType":"GGroup"},{"name":"go_yesBtn","tsType":"GGroup"}] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  private go_noBtn!: GGroup;
  private go_yesBtn!: GGroup;
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    this.go_noBtn = this.getChild<GGroup>("go_noBtn");
    this.go_yesBtn = this.getChild<GGroup>("go_yesBtn");
    // #endregion AUTO BIND
  }

  // ── 业务（AUTO 区块外，Creator 侧验证）────────────────────────
  // title/content/yesBtn/noBtn 无识别前缀（codegen 不绑）——业务侧 getChild 直取。
  /** 用 ConfirmLogic 渲染并接线：填标题/正文，wire 确定/取消，单按钮时隐藏取消组。 */
  setup(logic: ConfirmLogic): void {
    this.getChild<GTextField>("title").text = logic.title;
    this.getChild<GRichTextField>("content").text = logic.content;
    const yes = this.getChild<GButton>("yesBtn");
    const no = this.getChild<GButton>("noBtn");
    yes.title = logic.yesText;
    yes.onClick(() => logic.yes(), this);
    this.go_noBtn.visible = logic.hasCancel;
    if (logic.hasCancel && logic.noText) {
      no.title = logic.noText;
      no.onClick(() => logic.no(), this);
    }
  }
}
