// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://View_Home_Home/Home
import { FguiView } from "./FguiView";
import { HomeLogic } from "../logic/page/HomeLogic";
// #region AUTO IMPORT DONT CHANGE
import { GButton, GTextField } from "db://fairygui-cc/fairygui.mjs";
// #endregion AUTO IMPORT

export class HomeView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "View_Home_Home";
  static readonly COMP = "Home";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [{"name":"txt_userId","tsType":"GTextField"},{"name":"btn_enter","tsType":"GButton"}] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  private txt_userId!: GTextField;
  private btn_enter!: GButton;
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    this.txt_userId = this.getChild<GTextField>("txt_userId");
    this.btn_enter = this.getChild<GButton>("btn_enter");
    // #endregion AUTO BIND
  }

  // ── 业务（AUTO 区块外，Creator 侧验证）────────────────────────
  /** 「进入游戏」回调（Main 注入：退大厅壳、进 ballMove 玩法房）。 */
  onEnterBattle: () => void = () => {};

  /** 渲染 + 接线（opener 调用）：展示用户 id，按钮走 HomeLogic → onEnterBattle。 */
  setup(uid: string): void {
    this.txt_userId.text = uid;
    const logic = new HomeLogic();
    logic.setUserId(uid);
    logic.onEnterBattle = () => this.onEnterBattle();
    this.btn_enter.onClick(() => logic.enterBattle(), this);
  }
}
