// AUTO-GENERATED by tools/fgui-codegen — 业务逻辑(apply/onEvent)写在 AUTO 区块外。来源: ui://View_AreaList_LoginNotice/LoginNotice
import { FguiView } from "./FguiView";
import { Event, GList, GObject } from "db://fairygui-cc/fairygui.mjs";
import type { LoginNoticeLogic } from "../logic/page/LoginNoticeLogic";
// #region AUTO IMPORT DONT CHANGE
import { GButton, GComponent, GTextField } from "db://fairygui-cc/fairygui.mjs";
// #endregion AUTO IMPORT

export class LoginNoticeView extends FguiView {
  // #region AUTO REQUIRED DONT CHANGE
  static readonly PKG = "View_AreaList_LoginNotice";
  static readonly COMP = "LoginNotice";
  /** 结构契约(fgui-codegen checkContract 用)：本 View 依赖的 .fui 命名元素 + 类型。 */
  static readonly REQUIRED = [{"name":"btn_mask","tsType":"GButton"},{"name":"txt_title","tsType":"GTextField"},{"name":"jb_tabbar","tsType":"GComponent"},{"name":"txt_content","tsType":"GTextField"},{"name":"tge_tip","tsType":"GButton"},{"name":"btn_close","tsType":"GButton"}] as const;
  // #endregion AUTO REQUIRED

  // #region AUTO FIELD DONT CHANGE
  private btn_mask!: GButton;
  private txt_title!: GTextField;
  private jb_tabbar!: GComponent;
  private txt_content!: GTextField;
  private tge_tip!: GButton;
  private btn_close!: GButton;
  // #endregion AUTO FIELD

  protected bind(): void {
    // #region AUTO BIND DONT CHANGE
    this.btn_mask = this.getChild<GButton>("btn_mask");
    this.txt_title = this.getChild<GTextField>("txt_title");
    this.jb_tabbar = this.getChild<GComponent>("jb_tabbar");
    this.txt_content = this.getChild<GTextField>("txt_content");
    this.tge_tip = this.getChild<GButton>("tge_tip");
    this.btn_close = this.getChild<GButton>("btn_close");
    // #endregion AUTO BIND
  }

  // ── 业务（AUTO 区块外，Creator 侧验证）────────────────────────
  // 源项目最新版：jb_tabbar 已换成本包内建 CompTab（顶部标签栏，每条公告一个标签），选标签换 txt_content 正文。
  private logic!: LoginNoticeLogic;
  private titles: string[] = [];
  private selectedIndex = -1;
  /** jb_tabbar(CompTab) 内部的标签列表 lst_jb（defaultItem = CompTabItem）。 */
  private tabList!: GList;
  /** 「关闭」按钮回调，由页面打开方注入。 */
  onClose: () => void = () => {};

  /** 接线 LoginNoticeLogic：公告标签、正文及“今日不再提醒”状态。 */
  setup(logic: LoginNoticeLogic): void {
    this.logic = logic;
    this.btn_mask.onClick(() => this.onClose(), this);
    this.btn_close.onClick(() => this.onClose(), this);
    this.tge_tip.selected = logic.dontRemindToday;
    this.tge_tip.on(Event.STATUS_CHANGED, () => {
      logic.setDontRemindToday(this.tge_tip.selected);
    }, this);
    // ⚠ 本 fairygui-cc 版只有 .asCom，无 .asList —— 用 getChild<GList>(泛型)取类型化子项
    this.tabList = this.jb_tabbar.getChild<GList>("lst_jb");
    logic.onTabs = (titles) => {
      this.titles = titles;
      this.tabList.itemRenderer = (idx, obj) => this.renderTab(idx, obj as GComponent);
      this.tabList.numItems = titles.length;
    };
    logic.onContent = (item, index) => {
      this.txt_content.text = item.content;
      this.selectedIndex = index;
      // 非虚拟列表：逐标签刷新选中态（CompTabItem 的 on/off 底图 + 文字）
      for (let i = 0; i < this.tabList.numChildren; i++) {
        this.applyTabState(this.tabList.getChildAt(i).asCom, i === index);
      }
    };
    // ⚠ fairygui-cc 注册项点击用 on(Event.CLICK_ITEM,...)；onClickItem 是内部处理器（直接调会崩）
    this.tabList.on(Event.CLICK_ITEM, (obj: GObject) => {
      const idx = this.tabList.getChildIndex(obj);
      const it = this.logic.items[idx];
      if (it) this.logic.select(it.id);
    }, this);
  }

  /** 渲染单个标签（CompTabItem：txt_off/txt_on 双态文字 + img_off/img_on 双态底图）。 */
  private renderTab(idx: number, tab: GComponent): void {
    const title = this.titles[idx] ?? "";
    tab.getChild<GTextField>("txt_off").text = title;
    tab.getChild<GTextField>("txt_on").text = title;
    this.applyTabState(tab, idx === this.selectedIndex);
  }

  /** 标签选中态：on = 高亮底图 img_on + txt_on；off = 常态底图 img_off + txt_off。 */
  private applyTabState(tab: GComponent, on: boolean): void {
    const imgOn = tab.getChild("img_on"); if (imgOn) imgOn.visible = on;
    const imgOff = tab.getChild("img_off"); if (imgOff) imgOff.visible = !on;
    const txtOn = tab.getChild("txt_on"); if (txtOn) txtOn.visible = on;
    const txtOff = tab.getChild("txt_off"); if (txtOff) txtOff.visible = !on;
  }
}
