/** AUTO-GENERATED by apps/server/tools/plugin-codegen/cli.ts from apps/kits/mmo/kit.json (contributions) + apps/plugins/<id>/plugin.json (contributes). Do not edit. */
/** kit "mmo" 在 client 端收到的贡献：贡献点 id → 填充列表；由 codegen:plugins 刷新（docs/KIT.md §4）。 */
export const KIT_CONTRIBUTIONS = {
    /** 贡献点 "content"：0 个插件填充（按插件 id 排序）。 */
    content: [],
    /** 贡献点 "presentation"：0 个插件填充（按插件 id 排序）。 */
    presentation: [],
} as const;
