/** AUTO-GENERATED by apps/server/tools/plugin-codegen/cli.ts from apps/kits/<id>/kit.json. Do not edit. */
import type { ServerKitCatalogEntry } from "./catalogTypes";

/** 已登记 kit（按 id 排序）；与 @game/shared/kits/catalog.generated 的 KIT_CATALOG 同源同序。 */
export const SERVER_KIT_CATALOG: readonly ServerKitCatalogEntry[] = [
    {
        id: "arena",
        version: "1.0.1",
        api: {
            board: { version: 1, minSupported: 1 },
            ranking: { version: 1, minSupported: 1 },
        },
        modes: [
            { id: "arenaCapture", constantName: "ArenaCapture" },
            { id: "arenaDuel", constantName: "ArenaDuel" },
        ],
        domains: [
            "arena",
        ],
        effects: [
            { kitId: "arena", name: "trophy", userKey: "stats", field: "trophies", max: 1000000 },
        ],
        sqlFiles: [
            "sql/001-init.sql",
        ],
        sqlTables: [
            { name: "k_arena_board", zone: "per-zone" },
            { name: "k_arena_attempt", zone: "per-zone" },
        ],
        userKeys: [
            "stats",
        ],
        workers: [],
        contributions: {},
        fragments: [],
    },
    {
        id: "mmo",
        version: "0.1.12",
        api: {
            ai: { version: 1, minSupported: 1 },
            characters: { version: 1, minSupported: 1 },
            combat: { version: 1, minSupported: 1 },
            content: { version: 2, minSupported: 2 },
            inventory: { version: 2, minSupported: 1 },
            movement: { version: 1, minSupported: 1 },
            social: { version: 1, minSupported: 1 },
            world: { version: 2, minSupported: 1 },
        },
        modes: [
            { id: "mmoWorld", constantName: "MmoWorld" },
        ],
        domains: [
            "mmo",
            "mmoSocial",
        ],
        effects: [],
        sqlFiles: [
            "sql/001-characters.sql",
            "sql/002-items.sql",
            "sql/003-world.sql",
            "sql/004-character-checkpoint-instance-rev.sql",
        ],
        sqlTables: [
            { name: "k_mmo_character", zone: "per-zone" },
            { name: "k_mmo_character_checkpoint", zone: "per-zone" },
            { name: "k_mmo_item_instance", zone: "per-zone" },
            { name: "k_mmo_receipt", zone: "per-zone" },
            { name: "k_mmo_instance", zone: "per-zone" },
            { name: "k_mmo_instance_checkpoint", zone: "per-zone" },
            { name: "k_mmo_world_event", zone: "per-zone", role: "world-event" },
        ],
        userKeys: [],
        workers: [
            { id: "worldEvents", entry: "apps/server/src/kits/mmo/workers/worldEvents.ts" },
        ],
        contributions: {},
        fragments: [],
    },
    {
        id: "slg",
        version: null,
        api: {
            march: { version: 1, minSupported: 1 },
            worldmap: { version: 1, minSupported: 1 },
        },
        modes: [],
        domains: [
            "slg",
        ],
        effects: [
            { kitId: "slg", name: "trophy", userKey: "stats", field: "trophies", max: 1000000 },
        ],
        sqlFiles: [
            "sql/001-init.sql",
            "sql/002-march.sql",
        ],
        sqlTables: [
            { name: "k_slg_revision", zone: "per-zone" },
            { name: "k_slg_tile", zone: "per-zone" },
            { name: "k_slg_capture", zone: "per-zone" },
            { name: "k_slg_tile_log", zone: "per-zone" },
            { name: "k_slg_march", zone: "per-zone" },
            { name: "k_slg_march_receipt", zone: "per-zone" },
            { name: "k_slg_march_log", zone: "per-zone" },
        ],
        userKeys: [
            "stats",
        ],
        workers: [],
        contributions: {},
        fragments: [],
    },
    {
        id: "uniflex",
        version: null,
        api: {
            cocos: { version: 1, minSupported: 1 },
            core: { version: 1, minSupported: 1 },
            navigation: { version: 1, minSupported: 1 },
            provider: { version: 1, minSupported: 1 },
            web: { version: 1, minSupported: 1 },
        },
        modes: [],
        domains: [],
        effects: [],
        sqlFiles: [],
        sqlTables: [],
        userKeys: [],
        workers: [],
        contributions: {},
        fragments: [],
    },
];
