/** AUTO-GENERATED by apps/server/tools/plugin-codegen/cli.ts from apps/kits/<id>/kit.json. Do not edit. */
import type { ServerKitCatalogEntry } from "./catalogTypes";

/** 已登记 kit（按 id 排序）；与 @game/shared/kits/catalog.generated 的 KIT_CATALOG 同源同序。 */
export const SERVER_KIT_CATALOG: readonly ServerKitCatalogEntry[] = [];
