/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/manifest.json (wireExposed) + apps/server/src/rooms/modes/<id>/index.ts. Do not edit. */
import type { GameModeRegistry } from "../GameMode";
import { registerArenaCaptureGameMode } from "./arenaCapture/index";
import { registerArenaDuelGameMode } from "./arenaDuel/index";
import { registerBallMoveGameMode } from "./ballMove/index";
import { registerIdleGameMode } from "./idle/index";
import { registerSnakeGameMode } from "./snake/index";
import { registerTallyGameMode } from "./tally/index";

/** 已装配服务端 GameMode 的玩法 id（= canonical GameplayModeId；fixture 玩法不在此表）。 */
export const GENERATED_GAME_MODE_IDS: readonly string[] = [
    "arenaCapture",
    "arenaDuel",
    "ballMove",
    "idle",
    "snake",
    "tally",
];

/**
 * 在进程组合根登记全部 generated 服务端 GameMode（缺省登记进生产 gameModeRegistry；
 * 测试可注入自己的 registry）：后续登记失败回滚本次已登记项（逆序），⛔ 不影响调用前已有登记。
 */
export function registerGeneratedGameModes(registry?: GameModeRegistry): () => void {
    const disposers: Array<() => void> = [];
    try {
        disposers.push(registerArenaCaptureGameMode(registry));
        disposers.push(registerArenaDuelGameMode(registry));
        disposers.push(registerBallMoveGameMode(registry));
        disposers.push(registerIdleGameMode(registry));
        disposers.push(registerSnakeGameMode(registry));
        disposers.push(registerTallyGameMode(registry));
    } catch (error) {
        for (const dispose of disposers.splice(0).reverse()) dispose();
        throw error;
    }
    return () => {
        for (const dispose of disposers.splice(0).reverse()) dispose();
    };
}
