import { defineTheme, fontRef, imageRef } from '../../../kits/uniflex/api/core/index';

/** Second skin. Art IDs currently match classic; swap them here when a midnight pack exists. */
export const midnightTheme = defineTheme({
    font: fontRef('fonts/regular', 400),
    text: '#f3e7ff',
    button: {
        label: '#fff4e8',
        labelOutline: '#3a203d',
        font: fontRef('fonts/regular', 400),
        skins: {
            confirm: { source: imageRef('ui/button/confirm'), outline: '#7a2d4a' },
            cancel: { source: imageRef('ui/button/cancel'), outline: '#3d5c4a' },
            cyan: { source: imageRef('ui/button/cyan'), outline: '#2a4a68' },
            red: { source: imageRef('ui/button/red'), outline: '#6a2a28' },
            yellow: { source: imageRef('ui/button/yellow'), outline: '#643e14' },
        },
        width: 255, height: 102, fontSize: 40,
        labelLeft: 8, labelRight: 8, labelTop: 4, labelBottom: 12, iconGap: 16,
    },
    badge: {
        count: imageRef('ui/mail/number-badge'),
        dot: imageRef('ui/mail/unread-dot'),
        font: fontRef('fonts/regular', 700),
        color: '#ffd7f3', outline: '#3a203d', outlineWidth: 2,
        countSize: 34, dotSize: 24, countInset: 2, fontSize: 24, maxCount: 99,
    },
    popup: {
        prompt: imageRef('ui/popup/prompt'), small: imageRef('ui/popup/small'),
        close: imageRef('ui/popup/close'),
        title: '#ffe9c2', outline: '#ff7b9c', mask: '#090d18cc',
        font: fontRef('fonts/regular', 400),
        width: 708, height: 510,
        titleLeft: 36, titleRight: 96, titleTop: 14, titleHeight: 58, titleSize: 40,
        titleAlign: 'left', titleOutlineWidth: 2,
        closeRight: 0, closeTop: 0, closeHit: 72, closeIcon: 50,
    },
    checkbox: {
        on: imageRef('ui/character/check-on'),
        off: imageRef('ui/character/check-off'),
        size: 44, hitSize: 52,
    },
    input: {
        font: fontRef('fonts/regular', 700),
        color: '#5b3d6e',
        placeholder: '#9a86a8',
        background: imageRef('ui/alliance/input-bg'),
        fontSize: 26, textAlign: 'left', textLeft: 18,
    },
    progress: {
        font: fontRef('fonts/regular', 700),
        color: '#ffd7f3', outline: '#3a203d', outlineWidth: 2,
        track: imageRef('ui/hero/progress-track'), fill: imageRef('ui/hero/progress-fill'),
        inset: 2, labelSize: 24,
    },
    quantity: {
        minus: imageRef('ui/backpack/button-minus'), plus: imageRef('ui/backpack/button-plus'),
        track: imageRef('ui/backpack/slider-track'), fill: imageRef('ui/backpack/slider-fill'),
        thumb: imageRef('ui/backpack/slider-handle'), qtyBackground: imageRef('ui/backpack/quantity-bg'),
        font: fontRef('fonts/regular', 700), color: '#fff7ed', outline: '#3a203d', outlineWidth: 2,
        width: 700, height: 85, buttonWidth: 76,
        trackWidth: 391, thumbWidth: 37, thumbHeight: 71,
        sliderLeft: 86, sliderTop: 0, sliderHeight: 85, trackTop: 18, trackHeight: 44,
        fillLeft: 2, fillTop: 20, fillHeight: 40, fillPad: 2, thumbTop: 6,
        plusLeft: 486, qtyLeft: 579, qtyTop: 14, qtyWidth: 121, qtyHeight: 54, qtyFontSize: 33,
        maxLeft: 593,
    },
    tab: {
        selected: imageRef('ui/mail/tab-active'), unselected: imageRef('ui/mail/tab-inactive'),
        badge: imageRef('ui/mail/number-badge'), notice: imageRef('ui/mail/unread-dot'),
        color: '#5b3d6e', activeColor: '#3a203d', font: fontRef('fonts/regular', 700),
        gap: 14, height: 52, activeHeight: 67, fontSize: 28, activeFontSize: 32,
        activeLeft: -3, activeTop: -15, activeWidth: 6,
        badgeInset: 26, badgeTop: -14,
        skins: {
            mail: { selected: imageRef('ui/mail/tab-active'), unselected: imageRef('ui/mail/tab-inactive') },
            character: { selected: imageRef('ui/character/tab-selected'), unselected: imageRef('ui/character/tab-unselected') },
            heroList: { selected: imageRef('ui/hero/tabs-selected'), track: imageRef('ui/hero/tabs-base') },
            heroDetail: { selected: imageRef('ui/hero-detail/nav-selected') },
        },
    },
    empty: {
        icon: imageRef('ui/backpack/empty'), font: fontRef('fonts/regular', 700), color: '#d8bddf', fontSize: 40,
        iconWidth: 108, iconHeight: 116, labelHeight: 40, labelAlign: 'center',
    },
    star: {
        filled: imageRef('ui/hero/star-filled'), empty: imageRef('ui/hero/star-empty'),
    },
    item: {
        font: fontRef('fonts/regular', 700), color: '#ffd7f3', outline: '#3a203d', outlineWidth: 2,
        frames: {
            green: imageRef('ui/backpack/item-green'), blue: imageRef('ui/backpack/item-blue'),
            purple: imageRef('ui/backpack/item-purple'), orange: imageRef('ui/backpack/item-orange'),
            red: imageRef('ui/backpack/item-red'),
        },
        width: 154, height: 159,
        iconLeft: 13, iconTop: 24, iconWidth: 129, iconHeight: 107,
        countLeft: 87, countTop: 107, countWidth: 57, countHeight: 42, countSize: 32,
        countAlign: 'right',
    },
    resource: {
        background: imageRef('ui/backpack/resource-bg'), plus: imageRef('ui/backpack/resource-plus'),
        font: fontRef('fonts/regular', 700), color: '#ffd7f3', outline: '#3a203d', outlineWidth: 2,
        width: 153, height: 45, bgLeft: 7, bgTop: 5, bgWidth: 138, bgHeight: 32,
        iconLeft: 4, iconTop: 4, iconWidth: 37, iconHeight: 31,
        plusOffsetLeft: 16, plusOffsetTop: 12, plusWidth: 20, plusHeight: 21,
        valueLeft: 44, valueTop: 5, valueWidth: 101, valueHeight: 32, valueSize: 22,
    },
    chrome: {
        header: imageRef('ui/mail/header'), footer: imageRef('ui/mail/footer'), back: imageRef('ui/mail/back'),
        font: fontRef('fonts/regular', 700), title: '#ffe9c2', outline: '#ff7b9c',
        headerWidth: 750, headerHeight: 90,
        titleLeft: 80, titleInset: 16, titleWidth: 590, titleHeight: 58, titleSize: 40,
        titleAlign: 'center', titleOutlineWidth: 2,
        footerWidth: 750, footerHeight: 110,
        backLeft: 24, backTop: 20, backWidth: 64, backHeight: 56,
    },
    navigation: {
        base: imageRef('ui/hero/nav-base'), selected: imageRef('ui/hero/nav-selected'),
        wheel: imageRef('ui/hero/nav-wheel'), island: imageRef('ui/hero/nav-island'),
        hero: imageRef('ui/hero/nav-hero'), explore: imageRef('ui/hero/nav-wheel'), ship: imageRef('ui/hero/nav-ship'),
        notice: imageRef('ui/mail/unread-dot'),
        width: 750, height: 125,
    },
    wideMenu: {
        background: imageRef('ui/settings/button'), font: fontRef('fonts/regular', 700), color: '#5b3d6e',
        width: 326, height: 114, iconCenterX: 60, fontSize: 28,
        labelLeft: 108, labelTop: 28, labelWidth: 200, labelHeight: 58, labelAlign: 'left',
    },
    iconCaption: {
        font: fontRef('fonts/regular', 700), color: '#ffb4d2',
        labelHeight: 26, fontSize: 26, labelAlign: 'center',
    },
    preview: {
        background: '#090d18',
        surface: '#17142b',
        surfaceAlt: '#251f3d',
        text: '#ffe9c2',
        muted: '#d8bddf',
        accent: '#ff7b9c',
        accentAlt: '#7dd3fc',
        onAccent: '#201426',
    },
});
