/** Snake S1 server-only business draft catalog. */
// Generated by tools/snake-s1-assets/cli.mjs. DO NOT EDIT.

export const SNAKE_SKIN_BUSINESS_CATALOG_DATA = [
  {
    "skinId": 1,
    "aiEligible": false,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 1"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 2,
    "aiEligible": false,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 2"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 3,
    "aiEligible": false,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 3"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 4,
    "aiEligible": false,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 4"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 10,
    "aiEligible": false,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 10"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 11,
    "aiEligible": false,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 11"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 101,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 101"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 111,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 111"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 112,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 112"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 132,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 132"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 133,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 133"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 139,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 139"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 401,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 401"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 403,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 403"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 411,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 411"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  },
  {
    "skinId": 701,
    "aiEligible": true,
    "displayName": {
      "state": "technical-draft",
      "value": "皮肤 701"
    },
    "rarity": {
      "state": "draft",
      "value": null
    },
    "ownershipItemId": {
      "state": "unavailable",
      "value": null
    },
    "fragmentItemId": {
      "state": "unavailable",
      "value": null
    },
    "acquisition": {
      "state": "unavailable",
      "value": null
    },
    "saleState": {
      "state": "unavailable",
      "value": null
    },
    "price": {
      "state": "unavailable",
      "value": null
    }
  }
] as const;

export const EMBEDDED_PUBLIC_SNAKE_SKIN_CATALOG_HASH = "a1cdecbc5e31db3f90ac2fd15465768ef9206b2520000d4ab9f88d6c2135b075";

export const SERVER_SNAKE_SKIN_BUSINESS_HASH = "9ed3762e5f5d24d168aafd14fcaccac1d4de83413d0acb17f6308cea1ccbfa19";
