/** AUTO-GENERATED by apps/server/tools/plugin-codegen/cli.ts from apps/kits/mmo/kit.json (contributions) + apps/plugins/<id>/plugin.json (contributes). Do not edit. */
import { orchestration as mmodemo_orchestration } from "../../core/mmodemo/mmoOrchestration";
import { orchestration as mmohold_orchestration } from "../../core/mmohold/mmoOrchestration";

/** kit "mmo" 在 server 端收到的贡献：贡献点 id → 填充列表；由 codegen:plugins 刷新（docs/KIT.md §4）。 */
export const KIT_CONTRIBUTIONS = {
    /** 贡献点 "content"：2 个插件填充（按插件 id 排序）。 */
    content: [
        { pluginId: "mmodemo", value: {
            "schemaVersion": 1,
            "packId": "demoVale",
            "version": 1,
            "maps": [
                {
                    "mapId": "demoVale",
                    "name": "灰谷",
                    "size": {
                        "w": 2400,
                        "h": 2400
                    },
                    "aoi": {
                        "cellSize": 100,
                        "viewRadius": 400
                    },
                    "collision": {
                        "cellSize": 100,
                        "bitmap": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011000000000000000000000011000000000000000000000011000000000000000000000011000000000000000000000011000000000000000011000011000000000000000011000011000000000000000000000011000000000000000000000011000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
                    },
                    "nav": {
                        "cellSize": 100
                    },
                    "spawnPoints": [
                        {
                            "spawnPointId": "start",
                            "pos": {
                                "x": 600,
                                "y": 600
                            }
                        }
                    ],
                    "portals": [],
                    "respawnPoints": [
                        {
                            "x": 600,
                            "y": 600
                        }
                    ]
                }
            ],
            "regions": [
                {
                    "regionId": "den",
                    "mapId": "demoVale",
                    "shape": {
                        "kind": "circle",
                        "center": {
                            "x": 1900,
                            "y": 1900
                        },
                        "radius": 220
                    },
                    "enabledByDefault": true,
                    "tags": [
                        "boss"
                    ]
                },
                {
                    "regionId": "ambush",
                    "mapId": "demoVale",
                    "shape": {
                        "kind": "rect",
                        "min": {
                            "x": 1200,
                            "y": 400
                        },
                        "max": {
                            "x": 1700,
                            "y": 900
                        }
                    },
                    "enabledByDefault": true,
                    "tags": [
                        "ambush"
                    ]
                }
            ],
            "classes": [
                {
                    "classId": "fighter",
                    "name": "战士",
                    "presentationId": "vale-fighter",
                    "hpMax": 120,
                    "mpMax": 40,
                    "attack": 11,
                    "defense": 3,
                    "speedPerSec": 120,
                    "spells": [
                        "strike",
                        "warcry"
                    ]
                },
                {
                    "classId": "caster",
                    "name": "法师",
                    "presentationId": "vale-caster",
                    "hpMax": 90,
                    "mpMax": 110,
                    "attack": 7,
                    "defense": 1,
                    "speedPerSec": 110,
                    "spells": [
                        "fireball",
                        "heal"
                    ]
                }
            ],
            "creatures": [
                {
                    "templateId": "wolf",
                    "name": "灰狼",
                    "presentationId": "wolf",
                    "level": 3,
                    "hpMax": 45,
                    "mpMax": 0,
                    "attack": 7,
                    "defense": 1,
                    "speedPerSec": 130,
                    "behavior": "aggro",
                    "aggroRadius": 150,
                    "leashRadius": 500,
                    "spells": [
                        "bite"
                    ],
                    "lootTableId": "wolf-drops",
                    "respawnSec": 25,
                    "tier": "normal",
                    "checkpointOnDeath": false,
                    "interacts": []
                },
                {
                    "templateId": "valeBoar",
                    "name": "林猪",
                    "presentationId": "vale-boar",
                    "level": 2,
                    "hpMax": 60,
                    "mpMax": 0,
                    "attack": 5,
                    "defense": 2,
                    "speedPerSec": 80,
                    "behavior": "idle",
                    "aggroRadius": 0,
                    "leashRadius": 0,
                    "spells": [],
                    "lootTableId": "boar-drops",
                    "respawnSec": 30,
                    "tier": "normal",
                    "checkpointOnDeath": false,
                    "interacts": []
                },
                {
                    "templateId": "alphaWolf",
                    "name": "头狼",
                    "presentationId": "alpha-wolf",
                    "level": 8,
                    "hpMax": 600,
                    "mpMax": 0,
                    "attack": 18,
                    "defense": 4,
                    "speedPerSec": 140,
                    "behavior": "aggro",
                    "aggroRadius": 200,
                    "leashRadius": 600,
                    "spells": [
                        "bite",
                        "howl"
                    ],
                    "lootTableId": "alpha-drops",
                    "respawnSec": 600,
                    "tier": "boss",
                    "checkpointOnDeath": true,
                    "interacts": []
                }
            ],
            "spawns": [
                {
                    "spawnId": "wolf-pack",
                    "mapId": "demoVale",
                    "templateId": "wolf",
                    "pos": {
                        "x": 1400,
                        "y": 1500
                    },
                    "count": 4,
                    "waypoints": [],
                    "managed": "kit"
                },
                {
                    "spawnId": "boar-field",
                    "mapId": "demoVale",
                    "templateId": "valeBoar",
                    "pos": {
                        "x": 800,
                        "y": 1800
                    },
                    "count": 3,
                    "waypoints": [],
                    "managed": "kit"
                }
            ],
            "spells": [
                {
                    "spellId": "strike",
                    "name": "挥击",
                    "kind": "damage",
                    "castMs": 0,
                    "cooldownMs": 1500,
                    "mpCost": 0,
                    "range": 60,
                    "power": 9
                },
                {
                    "spellId": "warcry",
                    "name": "战吼",
                    "kind": "buff",
                    "castMs": 0,
                    "cooldownMs": 12000,
                    "mpCost": 6,
                    "range": 0,
                    "power": 4,
                    "durationMs": 8000
                },
                {
                    "spellId": "fireball",
                    "name": "火球",
                    "kind": "damage",
                    "castMs": 1000,
                    "cooldownMs": 4000,
                    "mpCost": 12,
                    "range": 300,
                    "power": 22
                },
                {
                    "spellId": "heal",
                    "name": "治愈",
                    "kind": "heal",
                    "castMs": 1200,
                    "cooldownMs": 6000,
                    "mpCost": 14,
                    "range": 200,
                    "power": 28
                },
                {
                    "spellId": "bite",
                    "name": "撕咬",
                    "kind": "damage",
                    "castMs": 0,
                    "cooldownMs": 2000,
                    "mpCost": 0,
                    "range": 60,
                    "power": 7
                },
                {
                    "spellId": "howl",
                    "name": "狼嚎",
                    "kind": "debuff",
                    "castMs": 0,
                    "cooldownMs": 9000,
                    "mpCost": 0,
                    "range": 250,
                    "power": 3,
                    "durationMs": 5000
                }
            ],
            "items": [
                {
                    "itemId": "wolf-fang",
                    "name": "狼牙",
                    "presentationId": "wolf-fang",
                    "slot": "none",
                    "stackMax": 99,
                    "classIds": [],
                    "price": 2,
                    "attrs": {}
                },
                {
                    "itemId": "wolf-pelt",
                    "name": "狼皮",
                    "presentationId": "wolf-pelt",
                    "slot": "none",
                    "stackMax": 50,
                    "classIds": [],
                    "price": 6,
                    "attrs": {}
                },
                {
                    "itemId": "boar-tusk",
                    "name": "猪牙",
                    "presentationId": "boar-tusk",
                    "slot": "none",
                    "stackMax": 50,
                    "classIds": [],
                    "price": 4,
                    "attrs": {}
                },
                {
                    "itemId": "alpha-fang",
                    "name": "头狼之牙",
                    "presentationId": "alpha-fang",
                    "slot": "none",
                    "stackMax": 99,
                    "classIds": [],
                    "price": 40,
                    "attrs": {}
                },
                {
                    "itemId": "iron-sword",
                    "name": "铁剑",
                    "presentationId": "iron-sword",
                    "slot": "weapon",
                    "stackMax": 1,
                    "classIds": [
                        "fighter"
                    ],
                    "price": 60,
                    "attrs": {
                        "attack": 4
                    }
                },
                {
                    "itemId": "oak-staff",
                    "name": "橡木杖",
                    "presentationId": "oak-staff",
                    "slot": "weapon",
                    "stackMax": 1,
                    "classIds": [
                        "caster"
                    ],
                    "price": 50,
                    "attrs": {
                        "attack": 3
                    }
                },
                {
                    "itemId": "leather-vest",
                    "name": "皮甲",
                    "presentationId": "leather-vest",
                    "slot": "armor",
                    "stackMax": 1,
                    "classIds": [],
                    "price": 45,
                    "attrs": {
                        "defense": 2
                    }
                },
                {
                    "itemId": "hunter-cloak",
                    "name": "猎人斗篷",
                    "presentationId": "hunter-cloak",
                    "slot": "armor",
                    "stackMax": 1,
                    "classIds": [],
                    "price": 55,
                    "attrs": {
                        "defense": 1,
                        "hpMax": 10
                    }
                },
                {
                    "itemId": "amber-charm",
                    "name": "琥珀护符",
                    "presentationId": "amber-charm",
                    "slot": "trinket",
                    "stackMax": 1,
                    "classIds": [],
                    "price": 80,
                    "attrs": {
                        "hpMax": 20
                    }
                },
                {
                    "itemId": "vale-tonic",
                    "name": "灰谷药水",
                    "presentationId": "vale-tonic",
                    "slot": "consumable",
                    "stackMax": 20,
                    "classIds": [],
                    "price": 8,
                    "attrs": {}
                }
            ],
            "lootTables": [
                {
                    "lootTableId": "wolf-drops",
                    "entries": [
                        {
                            "itemId": "wolf-fang",
                            "weight": 6,
                            "countMin": 1,
                            "countMax": 2
                        },
                        {
                            "itemId": "wolf-pelt",
                            "weight": 3,
                            "countMin": 1,
                            "countMax": 1
                        },
                        {
                            "itemId": "vale-tonic",
                            "weight": 1,
                            "countMin": 1,
                            "countMax": 1
                        }
                    ]
                },
                {
                    "lootTableId": "boar-drops",
                    "entries": [
                        {
                            "itemId": "boar-tusk",
                            "weight": 1,
                            "countMin": 1,
                            "countMax": 2
                        }
                    ]
                },
                {
                    "lootTableId": "alpha-drops",
                    "entries": [
                        {
                            "itemId": "alpha-fang",
                            "weight": 5,
                            "countMin": 1,
                            "countMax": 2
                        },
                        {
                            "itemId": "iron-sword",
                            "weight": 1,
                            "countMin": 1,
                            "countMax": 1
                        }
                    ]
                }
            ],
            "npcs": [
                {
                    "npcId": "merchant",
                    "mapId": "demoVale",
                    "name": "行商",
                    "presentationId": "merchant",
                    "pos": {
                        "x": 700,
                        "y": 500
                    },
                    "interacts": [
                        "trade"
                    ]
                }
            ]
        } },
        { pluginId: "mmohold", value: {
            "schemaVersion": 1,
            "packId": "holdRidge",
            "version": 1,
            "maps": [
                {
                    "mapId": "holdRidge",
                    "name": "争旗山脊",
                    "size": {
                        "w": 1600,
                        "h": 1200
                    },
                    "aoi": {
                        "cellSize": 100,
                        "viewRadius": 500
                    },
                    "collision": {
                        "cellSize": 100,
                        "bitmap": "000000000000000000000001100000000000000110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011000000000000001100000000000000000000000"
                    },
                    "nav": {
                        "cellSize": 100
                    },
                    "spawnPoints": [
                        {
                            "spawnPointId": "start",
                            "pos": {
                                "x": 600,
                                "y": 600
                            }
                        }
                    ],
                    "portals": [],
                    "respawnPoints": [
                        {
                            "x": 600,
                            "y": 600
                        }
                    ]
                }
            ],
            "regions": [
                {
                    "regionId": "pointA",
                    "mapId": "holdRidge",
                    "shape": {
                        "kind": "circle",
                        "center": {
                            "x": 600,
                            "y": 600
                        },
                        "radius": 150
                    },
                    "enabledByDefault": true,
                    "tags": [
                        "capture"
                    ]
                },
                {
                    "regionId": "pointB",
                    "mapId": "holdRidge",
                    "shape": {
                        "kind": "circle",
                        "center": {
                            "x": 1000,
                            "y": 600
                        },
                        "radius": 150
                    },
                    "enabledByDefault": true,
                    "tags": [
                        "capture"
                    ]
                }
            ],
            "classes": [
                {
                    "classId": "fighter",
                    "name": "山脊先锋",
                    "presentationId": "hold-fighter",
                    "hpMax": 140,
                    "mpMax": 40,
                    "attack": 12,
                    "defense": 4,
                    "speedPerSec": 140,
                    "spells": [
                        "holdStrike",
                        "holdRally"
                    ]
                },
                {
                    "classId": "caster",
                    "name": "山脊术师",
                    "presentationId": "hold-caster",
                    "hpMax": 100,
                    "mpMax": 100,
                    "attack": 14,
                    "defense": 2,
                    "speedPerSec": 140,
                    "spells": [
                        "holdBolt",
                        "holdHeal"
                    ]
                }
            ],
            "creatures": [
                {
                    "templateId": "sentinel",
                    "name": "据点守卫",
                    "presentationId": "hold-sentinel",
                    "level": 3,
                    "hpMax": 180,
                    "mpMax": 0,
                    "attack": 9,
                    "defense": 5,
                    "speedPerSec": 0,
                    "behavior": "idle",
                    "aggroRadius": 0,
                    "leashRadius": 150,
                    "spells": [],
                    "respawnSec": 0,
                    "tier": "elite",
                    "checkpointOnDeath": false,
                    "interacts": []
                }
            ],
            "spawns": [
                {
                    "spawnId": "pointA-sentinel",
                    "mapId": "holdRidge",
                    "templateId": "sentinel",
                    "pos": {
                        "x": 600,
                        "y": 650
                    },
                    "count": 2,
                    "waypoints": [],
                    "managed": "orchestration"
                },
                {
                    "spawnId": "pointB-sentinel",
                    "mapId": "holdRidge",
                    "templateId": "sentinel",
                    "pos": {
                        "x": 1000,
                        "y": 650
                    },
                    "count": 2,
                    "waypoints": [],
                    "managed": "orchestration"
                }
            ],
            "spells": [
                {
                    "spellId": "holdStrike",
                    "name": "破阵斩",
                    "kind": "damage",
                    "castMs": 0,
                    "cooldownMs": 900,
                    "mpCost": 0,
                    "range": 100,
                    "power": 17
                },
                {
                    "spellId": "holdRally",
                    "name": "集结",
                    "kind": "buff",
                    "castMs": 0,
                    "cooldownMs": 12000,
                    "mpCost": 10,
                    "range": 0,
                    "power": 5,
                    "durationMs": 6000
                },
                {
                    "spellId": "holdBolt",
                    "name": "山雷",
                    "kind": "damage",
                    "castMs": 500,
                    "cooldownMs": 1200,
                    "mpCost": 6,
                    "range": 350,
                    "power": 20
                },
                {
                    "spellId": "holdHeal",
                    "name": "回春",
                    "kind": "heal",
                    "castMs": 500,
                    "cooldownMs": 5000,
                    "mpCost": 12,
                    "range": 300,
                    "power": 30
                }
            ],
            "items": [
                {
                    "itemId": "hold-medal",
                    "name": "据点勋章",
                    "presentationId": "hold-medal",
                    "slot": "none",
                    "stackMax": 99,
                    "classIds": [],
                    "price": 30,
                    "attrs": {}
                },
                {
                    "itemId": "hold-banner",
                    "name": "山脊战旗",
                    "presentationId": "hold-banner",
                    "slot": "none",
                    "stackMax": 99,
                    "classIds": [],
                    "price": 40,
                    "attrs": {}
                },
                {
                    "itemId": "hold-seal",
                    "name": "守望徽印",
                    "presentationId": "hold-seal",
                    "slot": "none",
                    "stackMax": 99,
                    "classIds": [],
                    "price": 50,
                    "attrs": {}
                }
            ],
            "lootTables": [],
            "npcs": []
        } },
    ],
    /** 贡献点 "orchestration"：2 个插件填充（按插件 id 排序）。 */
    orchestration: [
        { pluginId: "mmodemo", value: mmodemo_orchestration },
        { pluginId: "mmohold", value: mmohold_orchestration },
    ],
} as const;
