import { defineTheme, fontRef, imageRef } from '../../../kits/uniflex/api/core/index';

export const classicTheme = defineTheme({
    font: fontRef('fonts/regular', 400),
    text: '#3f3254',
    button: {
        label: '#ffffff',
        labelOutline: '#000000',
        font: fontRef('fonts/regular', 400),
        confirm: { image: imageRef('ui/button/confirm'), outline: '#643e14' },
        cancel: { image: imageRef('ui/button/cancel'), outline: '#4e783b' },
        cyan: { image: imageRef('ui/button/cyan'), outline: '#2e5a68' },
        width: 255, height: 102, fontSize: 40,
        labelLeft: 8, labelRight: 8, labelTop: 4, labelBottom: 12, iconGap: 16,
    },
    badge: {
        count: imageRef('ui/mail/number-badge'),
        dot: imageRef('ui/mail/unread-dot'),
        font: fontRef('fonts/regular', 700),
        color: '#ffffff', outline: '#000000', outlineWidth: 2,
        countSize: 34, dotSize: 24, countInset: 2, fontSize: 24, maxCount: 99,
    },
    popup: {
        prompt: imageRef('ui/popup/prompt'), small: imageRef('ui/popup/small'),
        close: imageRef('ui/popup/close'),
        title: '#ffffff', outline: '#593d84', mask: '#00000099',
        font: fontRef('fonts/regular', 400),
        width: 708, height: 510,
        titleLeft: 90, titleRight: 90, titleTop: 18, titleHeight: 58, titleSize: 40,
        titleAlign: 'center', titleOutlineWidth: 2,
        closeRight: 15, closeTop: 6, closeHit: 72, closeIcon: 50,
    },
    checkbox: {
        on: imageRef('ui/character/check-on'),
        off: imageRef('ui/character/check-off'),
        size: 44, hitSize: 52,
    },
    input: {
        font: fontRef('fonts/regular', 700),
        color: '#6f6555',
        placeholder: '#6f6555',
        background: imageRef('ui/alliance/input-bg'),
        fontSize: 26, textAlign: 'center', textLeft: 0,
    },
    progress: {
        font: fontRef('fonts/regular', 700),
        color: '#ffffff', outline: '#000000', outlineWidth: 2,
        track: imageRef('ui/hero/progress-track'), fill: imageRef('ui/hero/progress-fill'),
        inset: 2, labelSize: 24,
    },
    quantity: {
        minus: imageRef('ui/backpack/button-minus'), plus: imageRef('ui/backpack/button-plus'),
        track: imageRef('ui/backpack/slider-track'), fill: imageRef('ui/backpack/slider-fill'),
        thumb: imageRef('ui/backpack/slider-handle'), qtyBackground: imageRef('ui/backpack/quantity-bg'),
        font: fontRef('fonts/regular', 700), color: '#ffffff', outline: '#000000', outlineWidth: 2,
        width: 700, height: 85, buttonWidth: 76,
        trackWidth: 391, thumbWidth: 37, thumbHeight: 71,
        sliderLeft: 86, sliderTop: 0, sliderHeight: 85, trackTop: 18, trackHeight: 44,
        fillLeft: 2, fillTop: 20, fillHeight: 40, fillPad: 2, thumbTop: 6,
        plusLeft: 486, qtyLeft: 579, qtyTop: 14, qtyWidth: 121, qtyHeight: 54, qtyFontSize: 33,
        maxLeft: 593,
    },
    tab: {
        selected: imageRef('ui/mail/tab-active'), unselected: imageRef('ui/mail/tab-inactive'),
        badge: imageRef('ui/mail/number-badge'), notice: imageRef('ui/mail/unread-dot'),
        color: '#3f3254', activeColor: '#3f3254', font: fontRef('fonts/regular', 700),
        gap: 14, height: 52, activeHeight: 67, fontSize: 28, activeFontSize: 32,
        activeLeft: -3, activeTop: -15, activeWidth: 6,
        badgeInset: 26, badgeTop: -14,
        skins: {
            mail: { selected: imageRef('ui/mail/tab-active'), unselected: imageRef('ui/mail/tab-inactive') },
            character: { selected: imageRef('ui/character/tab-selected'), unselected: imageRef('ui/character/tab-unselected') },
            heroList: { selected: imageRef('ui/hero/tabs-selected'), track: imageRef('ui/hero/tabs-base') },
            heroDetail: { selected: imageRef('ui/hero-detail/nav-selected') },
        },
    },
    empty: {
        icon: imageRef('ui/backpack/empty'), font: fontRef('fonts/regular', 700), color: '#837a91', fontSize: 40,
        iconWidth: 108, iconHeight: 116, labelHeight: 40, labelAlign: 'center',
    },
    star: {
        filled: imageRef('ui/hero/star-filled'), empty: imageRef('ui/hero/star-empty'),
    },
    item: {
        font: fontRef('fonts/regular', 700), color: '#ffffff', outline: '#000000', outlineWidth: 2,
        frames: {
            green: imageRef('ui/backpack/item-green'), blue: imageRef('ui/backpack/item-blue'),
            purple: imageRef('ui/backpack/item-purple'), orange: imageRef('ui/backpack/item-orange'),
            red: imageRef('ui/backpack/item-red'),
        },
        width: 154, height: 159,
        iconLeft: 13, iconTop: 24, iconWidth: 129, iconHeight: 107,
        countLeft: 87, countTop: 107, countWidth: 57, countHeight: 42, countSize: 32,
        countAlign: 'right',
    },
    resource: {
        background: imageRef('ui/backpack/resource-bg'), plus: imageRef('ui/backpack/resource-plus'),
        font: fontRef('fonts/regular', 700), color: '#ffffff', outline: '#000000', outlineWidth: 2,
        width: 153, height: 45, bgLeft: 7, bgTop: 5, bgWidth: 138, bgHeight: 32,
        iconLeft: 4, iconTop: 4, iconWidth: 37, iconHeight: 31,
        plusOffsetLeft: 16, plusOffsetTop: 12, plusWidth: 20, plusHeight: 21,
        valueLeft: 44, valueTop: 5, valueWidth: 101, valueHeight: 32, valueSize: 22,
    },
    chrome: {
        header: imageRef('ui/mail/header'), footer: imageRef('ui/mail/footer'), back: imageRef('ui/mail/back'),
        font: fontRef('fonts/regular', 700), title: '#ffffff', outline: '#593d84',
        headerWidth: 750, headerHeight: 90,
        titleLeft: 38, titleInset: 16, titleWidth: 200, titleHeight: 58, titleSize: 40,
        titleAlign: 'left', titleOutlineWidth: 2,
        footerWidth: 750, footerHeight: 110,
        backLeft: 13, backTop: 27, backWidth: 64, backHeight: 56,
    },
    navigation: {
        base: imageRef('ui/hero/nav-base'), selected: imageRef('ui/hero/nav-selected'),
        wheel: imageRef('ui/hero/nav-wheel'), island: imageRef('ui/hero/nav-island'),
        hero: imageRef('ui/hero/nav-hero'), explore: imageRef('ui/hero/nav-wheel'), ship: imageRef('ui/hero/nav-ship'),
        notice: imageRef('ui/mail/unread-dot'),
        width: 750, height: 125,
    },
    wideMenu: {
        background: imageRef('ui/settings/button'), font: fontRef('fonts/regular', 700), color: '#3f3254',
        width: 326, height: 114, iconCenterX: 60, fontSize: 28,
        labelLeft: 118, labelTop: 28, labelWidth: 190, labelHeight: 58, labelAlign: 'center',
    },
    iconCaption: {
        font: fontRef('fonts/regular', 700), color: '#ffffff',
        labelHeight: 26, fontSize: 26, labelAlign: 'center',
    },
    preview: {
        background: '#101318',
        surface: '#202735',
        surfaceAlt: '#2b3445',
        text: '#f6f8ff',
        muted: '#aab4c4',
        accent: '#4fd1c5',
        accentAlt: '#f5b942',
        onAccent: '#19202b',
    },
});
