/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json} + apps/client/src/gameplay/modes/<id>/index.ts. Do not edit. */
import { registerGameplayModule } from "../logic/gameplay/GameplayModule";
import type { AppGameplayRegistry, GameplayServicesContext } from "./services";
import { createGameplayModule as createBallMoveGameplayModule } from "./modes/ballMove/index";
import { createGameplayModule as createIdleGameplayModule } from "./modes/idle/index";

/** Per-gameplay catalog mirror. contractDigest = sha256(manifest.json + "\0" + state.json + "\0" + wire.ts). */
export const GAMEPLAY_CATALOG = {
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "c8fca655408e3bae34c9b3072681536e03b9258bdc97d827015ccf19feea677e",
    },
    "dropInFixture": {
        id: "dropInFixture",
        constantName: "DropInFixture",
        modeVersion: 1,
        maxPlayers: 8,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "10a6c06129af42a6f473481239d8a6570a08f2c70e5a5100d511e8e48300badb",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "0ecdaaa95a97d83b73df2a3f3d5535f0e4bf113fb50fa64c52a79477f0749ef7",
    },
    "privateFixture": {
        id: "privateFixture",
        constantName: "PrivateFixture",
        modeVersion: 1,
        maxPlayers: 4,
        profiles: ["default", "private"],
        stateFragments: ["ownerReady", "inviteRoom"],
        contractDigest: "93c50eb5f5de997cb09c843bb187b599efdf7111e65228668a958b84cc1597ed",
    },
    "snake": {
        id: "snake",
        constantName: "Snake",
        modeVersion: 1,
        maxPlayers: 8,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "620258cad08b812dd3edafb88ee0cdf0a725d0b728f651051ccdb61bf191cdb4",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;

/** 已装配客户端 module 的玩法（canonical GameplayModeId ∩ catalog；fixture 玩法不在此表）。 */
export const GAMEPLAY_MODULES = {
    "ballMove": createBallMoveGameplayModule,
    "idle": createIdleGameplayModule,
} as const;

export type GameplayModuleId = keyof typeof GAMEPLAY_MODULES;

/**
 * 登记全部 generated gameplay module（§7.6）：每个 module 只注入稳定服务，
 * 后续登记失败回滚本次已登记项（逆序），⛔ 不影响调用前已有登记。
 */
export function registerGeneratedGameplays(
    registry: AppGameplayRegistry,
    services: GameplayServicesContext,
): () => void {
    const disposers: Array<() => void> = [];
    try {
        disposers.push(registerGameplayModule(registry, createBallMoveGameplayModule(services), services.controllerBridge));
        disposers.push(registerGameplayModule(registry, createIdleGameplayModule(services), services.controllerBridge));
    } catch (error) {
        for (const dispose of disposers.splice(0).reverse()) dispose();
        throw error;
    }
    return () => {
        for (const dispose of disposers.splice(0).reverse()) dispose();
    };
}
