/** Generated by texture_layout.py; do not edit. Storage is independent of prefab geometry. */
export interface IMapoTextureLayout {
    readonly textureId: string;
    readonly atlasId: string;
    readonly rect: readonly [number, number, number, number];
    readonly nativeSize: readonly [number, number];
    readonly storageSize: readonly [number, number];
    readonly trimRect: readonly [number, number, number, number];
    readonly layoutVersion: number;
    /** SHA-256 of big-endian uint32 rect width/height followed by retained RGBA pixels. */
    readonly contentHash: string;
}
export type MapoTextureLayouts = Readonly<Record<string, IMapoTextureLayout>>;
