/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json}. Do not edit. */
import { Schema, MapSchema } from "@colyseus/schema";
import { type GamePhaseType, type RoomStateMode } from "@game/shared";
import { GameRoomState } from "./generated/ballMove";
import { IdleRoomState } from "./generated/idle";

export { PlayerState, GameRoomState } from "./generated/ballMove";
export { IdlePlayerState, IdleRoomState } from "./generated/idle";

/** Fields every root declares; the gameplay-agnostic GameRoom shell may only touch these. */
export interface RoomStatePlayerLifecycle {
    id: string;
    name: string;
}

/** Root lifecycle view used by the generic shell; the selected mode owns everything else. */
export interface RoomStateLifecycle {
    tick: number;
    phase: GamePhaseType;
    matchId: string;
    players: MapSchema<RoomStatePlayerLifecycle>;
}

export const ROOM_STATE_ROOT_CONSTRUCTORS = Object.freeze({
    "ballMove": GameRoomState,
    "idle": IdleRoomState,
} as const satisfies Record<RoomStateMode, new () => Schema>);

export type RoomStateRootForMode<M extends RoomStateMode> = InstanceType<(typeof ROOM_STATE_ROOT_CONSTRUCTORS)[M]>;
export type RoomStateRoot = RoomStateRootForMode<RoomStateMode>;
type RoomStateRootConstructor = (typeof ROOM_STATE_ROOT_CONSTRUCTORS)[RoomStateMode];

export function createRoomStateForMode<M extends RoomStateMode>(mode: M): RoomStateRootForMode<M>;
export function createRoomStateForMode(mode: string): RoomStateRoot;
export function createRoomStateForMode(mode: string): RoomStateRoot {
    const Root = (ROOM_STATE_ROOT_CONSTRUCTORS as Readonly<Partial<Record<string, RoomStateRootConstructor>>>)[mode];
    if (!Root) throw new TypeError(`[room-state] unsupported gameplay mode: ${mode}`);
    return new Root();
}
