/** AUTO-GENERATED by apps/server/tools/room-state-codegen.ts from apps/shared/schema/game-room-state.json. Do not edit. */
import { Schema, type, MapSchema } from "@colyseus/schema";
import { GamePhase, PLAYER_INIT_HP, type GamePhaseType, type RoomStateMode } from "@game/shared";

export class PlayerState extends Schema {
    /** Colyseus sessionId */
    @type("string") id: string = "";
    @type("string") name: string = "";
    /** Logical x coordinate */
    @type("number") x: number = 0;
    /** Logical y coordinate */
    @type("number") y: number = 0;
    @type("number") hp: number = PLAYER_INIT_HP;
    @type("number") maxHp: number = PLAYER_INIT_HP;
    /** Whether the player is alive */
    @type("boolean") alive: boolean = true;

    // Server-only fields below are intentionally undecorated and never enter the wire state.
    /** Normalized movement input on the x axis */
    dirX: number = 0;
    /** Normalized movement input on the y axis */
    dirY: number = 0;
    /** Last accepted skill cast ticks */
    lastCastTick: Record<number, number> = {};
    /** Demo level used by the damage formula */
    level: number = 1;
}

export class GameRoomState extends Schema {
    /** Logical frame number */
    @type("number") tick: number = 0;
    /** Room phase */
    @type("string") phase: GamePhaseType = GamePhase.Waiting;
    /** Stable match id; empty while waiting */
    @type("string") matchId: string = "";
    /** Players keyed by sessionId */
    @type({ map: PlayerState }) players = new MapSchema<PlayerState>();
}

export class IdlePlayerState extends Schema {
    /** Colyseus sessionId */
    @type("string") id: string = "";
    @type("string") name: string = "";
    /** Accepted idle pulse count */
    @type("number") pulses: number = 0;
}

export class IdleRoomState extends Schema {
    /** Logical frame number */
    @type("number") tick: number = 0;
    /** Room phase */
    @type("string") phase: GamePhaseType = GamePhase.Waiting;
    /** Stable match id; empty while waiting */
    @type("string") matchId: string = "";
    /** Pulses required to win */
    @type("number") pulseGoal: number = 3;
    /** Winning sessionId; empty before settlement */
    @type("string") winnerId: string = "";
    /** Idle players keyed by sessionId */
    @type({ map: IdlePlayerState }) players = new MapSchema<IdlePlayerState>();
}

export const ROOM_STATE_ROOT_CONSTRUCTORS = Object.freeze({
    "ballMove": GameRoomState,
    "idle": IdleRoomState,
} as const satisfies Record<RoomStateMode, new () => Schema>);

export type RoomStateRootForMode<M extends RoomStateMode> = InstanceType<(typeof ROOM_STATE_ROOT_CONSTRUCTORS)[M]>;
export type RoomStateRoot = RoomStateRootForMode<RoomStateMode>;
type RoomStateRootConstructor = (typeof ROOM_STATE_ROOT_CONSTRUCTORS)[RoomStateMode];

export function createRoomStateForMode<M extends RoomStateMode>(mode: M): RoomStateRootForMode<M>;
export function createRoomStateForMode(mode: string): RoomStateRoot;
export function createRoomStateForMode(mode: string): RoomStateRoot {
    const Root = (ROOM_STATE_ROOT_CONSTRUCTORS as Readonly<Partial<Record<string, RoomStateRootConstructor>>>)[mode];
    if (!Root) throw new TypeError(`[room-state] unsupported gameplay mode: ${mode}`);
    return new Root();
}
