/** AUTO-GENERATED by apps/server/tools/plugin-codegen/cli.ts from apps/shared/src/protocol/lobbyRpc/domains/*.ts + apps/shared/src/protocol/lobbyRpc/coreErrors.ts. Do not edit. */
import { assertExactKeys, guardWire, WireValidationError, type RuntimeValidator } from "../http";
import type { LobbyRpcRouteMode } from "./defineDomain";
import { guardRpcValidator, pushRecord } from "./primitives";
import { validateForceLogoutPush, validateServerNoticePush, type IForceLogoutPush, type IServerNoticePush } from "./coreErrors";
import type { IPurchaseResult } from "./economy";
import { validateArenaBoardReq, validateArenaBoardRes, validateArenaCaptureReq, validateArenaCaptureRes, type IArenaBoardReq, type IArenaBoardRes, type IArenaCaptureReq, type IArenaCaptureRes } from "./domains/arena";
import { validateArenaShopBuyBoostReq, validateArenaShopBuyBoostRes, type IArenaShopBuyBoostReq, type IArenaShopBuyBoostRes } from "./domains/arenaShop";
import { validateChatMessagePush, validateChatSendReq, validateChatSendRes, type IChatMessagePush, type IChatSendReq, type IChatSendRes } from "./domains/chat";
import { validateGuildEventPush, validateGuildGetEventsReq, validateGuildGetEventsRes, validateGuildJoinReq, validateGuildJoinRes, validateGuildLeaveReq, validateGuildLeaveRes, type IGuildEventPush, type IGuildGetEventsReq, type IGuildGetEventsRes, type IGuildJoinReq, type IGuildJoinRes, type IGuildLeaveReq, type IGuildLeaveRes } from "./domains/guild";
import { validateIncomeClaimOfflineReq, validateIncomeClaimOfflineRes, validateIncomeGetPendingReq, validateIncomeGetPendingRes, validateIncomeSettleOnlineReq, validateIncomeSettleOnlineRes, type IIncomeClaimOfflineReq, type IIncomeClaimOfflineRes, type IIncomeGetPendingReq, type IIncomeGetPendingRes, type IIncomeSettleOnlineReq, type IIncomeSettleOnlineRes } from "./domains/income";
import { validateMailClaimAttachReq, validateMailClaimAttachRes, validateMailListReq, validateMailListRes, validateMailMarkReadReq, validateMailMarkReadRes, validateMailNewPush, type IMailClaimAttachReq, type IMailListReq, type IMailListRes, type IMailMarkReadReq, type IMailMarkReadRes, type IMailNewPush } from "./domains/mail";
import { validatePartyAcceptReq, validatePartyAcceptRes, validatePartyCreateReq, validatePartyCreateRes, validatePartyDeclineReq, validatePartyDeclineRes, validatePartyEventPush, validatePartyGetEventsReq, validatePartyGetEventsRes, validatePartyGetReq, validatePartyGetRes, validatePartyInviteReq, validatePartyInviteRes, validatePartyInvitedPush, validatePartyKickReq, validatePartyKickRes, validatePartyLeaveReq, validatePartyLeaveRes, validatePartyTransferLeaderReq, validatePartyTransferLeaderRes, type IPartyAcceptReq, type IPartyAcceptRes, type IPartyCreateReq, type IPartyCreateRes, type IPartyDeclineReq, type IPartyDeclineRes, type IPartyEventPush, type IPartyGetEventsReq, type IPartyGetEventsRes, type IPartyGetReq, type IPartyGetRes, type IPartyInviteReq, type IPartyInviteRes, type IPartyInvitedPush, type IPartyKickReq, type IPartyLeaveReq, type IPartyLeaveRes, type IPartyTransferLeaderReq } from "./domains/party";
import { validateRedeemClaimReq, validateRedeemClaimRes, type IRedeemClaimReq, type IRedeemClaimRes } from "./domains/redeem";
import { validateRoomPrepareCreateReq, validateRoomPrepareCreateRes, validateRoomResolveReq, validateRoomResolveRes, type IRoomPrepareCreateReq, type IRoomPrepareCreateRes, type IRoomResolveReq, type IRoomResolveRes } from "./domains/room";
import { validateShopPurchaseReq, validateShopPurchaseRes, validateShopQueryOpReq, validateShopQueryOpRes, type IShopPurchaseReq, type IShopQueryOpReq } from "./domains/shop";
import { validateSlgMapTilesReq, validateSlgMapTilesRes, validateSlgMarchDispatchReq, validateSlgMarchDispatchRes, validateSlgMarchRecallReq, validateSlgMarchRecallRes, validateSlgTileCaptureReq, validateSlgTileCaptureRes, type ISlgMapTilesReq, type ISlgMapTilesRes, type ISlgMarchDispatchReq, type ISlgMarchDispatchRes, type ISlgMarchRecallReq, type ISlgMarchRecallRes, type ISlgTileCaptureReq, type ISlgTileCaptureRes } from "./domains/slg";
import { validateSnakeCosmeticEquipReq, validateSnakeCosmeticEquipRes, validateSnakeCosmeticGetSnapshotReq, validateSnakeCosmeticGetSnapshotRes, validateSnakeCosmeticUnlockReq, validateSnakeCosmeticUnlockRes, type ISnakeCosmeticGetSnapshotReq, type ISnakeCosmeticProfileRes, type ISnakeCosmeticSkinReq, type ISnakeCosmeticSnapshotRes } from "./domains/snakeCosmetic";
import { validateUserGetInfoReq, validateUserGetInfoRes, validateUserGetProfileReq, validateUserGetProfileRes, validateUserGetUserIdReq, validateUserGetUserIdRes, validateUserUpdateProfileReq, validateUserUpdateProfileRes, type IGetInfoReq, type IGetInfoRes, type IGetProfileReq, type IGetProfileRes, type IGetUserIdReq, type IGetUserIdRes, type IUpdateProfileReq, type IUpdateProfileRes } from "./domains/user";
import { validateWorldEnterReq, validateWorldEnterRes, validateWorldResolveTransferReq, validateWorldResolveTransferRes, validateWorldTransferPush, type IWorldEnterReq, type IWorldEnterRes, type IWorldResolveTransferReq, type IWorldResolveTransferRes, type IWorldTransferPush } from "./domains/world";

/** 领域全集（生成器删除保护锚 + 向量 sidecar 的域集合闸）。 */
export const LOBBY_RPC_DOMAINS: readonly string[] = [
    "arena",
    "arenaShop",
    "chat",
    "guild",
    "income",
    "mail",
    "party",
    "redeem",
    "room",
    "shop",
    "slg",
    "snakeCosmetic",
    "user",
    "world",
];

/** 全量路由契约（服务端 defineRpc 与客户端 WebSocketClient.rpc 的公共类型域） */
export interface LobbyRpcMap {
    "arena.board": { req: IArenaBoardReq; res: IArenaBoardRes };
    "arena.capture": { req: IArenaCaptureReq; res: IArenaCaptureRes };
    "arenaShop.buyBoost": { req: IArenaShopBuyBoostReq; res: IArenaShopBuyBoostRes };
    "chat.send": { req: IChatSendReq; res: IChatSendRes };
    "guild.join": { req: IGuildJoinReq; res: IGuildJoinRes };
    "guild.leave": { req: IGuildLeaveReq; res: IGuildLeaveRes };
    "guild.getEvents": { req: IGuildGetEventsReq; res: IGuildGetEventsRes };
    "income.getPending": { req: IIncomeGetPendingReq; res: IIncomeGetPendingRes };
    "income.settleOnline": { req: IIncomeSettleOnlineReq; res: IIncomeSettleOnlineRes };
    "income.claimOffline": { req: IIncomeClaimOfflineReq; res: IIncomeClaimOfflineRes };
    "mail.list": { req: IMailListReq; res: IMailListRes };
    "mail.claimAttach": { req: IMailClaimAttachReq; res: IPurchaseResult };
    "mail.markRead": { req: IMailMarkReadReq; res: IMailMarkReadRes };
    "party.create": { req: IPartyCreateReq; res: IPartyCreateRes };
    "party.invite": { req: IPartyInviteReq; res: IPartyInviteRes };
    "party.accept": { req: IPartyAcceptReq; res: IPartyAcceptRes };
    "party.decline": { req: IPartyDeclineReq; res: IPartyDeclineRes };
    "party.leave": { req: IPartyLeaveReq; res: IPartyLeaveRes };
    "party.kick": { req: IPartyKickReq; res: IPartyAcceptRes };
    "party.transferLeader": { req: IPartyTransferLeaderReq; res: IPartyAcceptRes };
    "party.get": { req: IPartyGetReq; res: IPartyGetRes };
    "party.getEvents": { req: IPartyGetEventsReq; res: IPartyGetEventsRes };
    "redeem.claim": { req: IRedeemClaimReq; res: IRedeemClaimRes };
    "room.prepareCreate": { req: IRoomPrepareCreateReq; res: IRoomPrepareCreateRes };
    "room.resolve": { req: IRoomResolveReq; res: IRoomResolveRes };
    "shop.purchase": { req: IShopPurchaseReq; res: IPurchaseResult };
    "shop.queryOp": { req: IShopQueryOpReq; res: IPurchaseResult };
    "slg.mapTiles": { req: ISlgMapTilesReq; res: ISlgMapTilesRes };
    "slg.tileCapture": { req: ISlgTileCaptureReq; res: ISlgTileCaptureRes };
    "slg.marchDispatch": { req: ISlgMarchDispatchReq; res: ISlgMarchDispatchRes };
    "slg.marchRecall": { req: ISlgMarchRecallReq; res: ISlgMarchRecallRes };
    "snakeCosmetic.getSnapshot": { req: ISnakeCosmeticGetSnapshotReq; res: ISnakeCosmeticSnapshotRes };
    "snakeCosmetic.equip": { req: ISnakeCosmeticSkinReq; res: ISnakeCosmeticProfileRes };
    "snakeCosmetic.unlock": { req: ISnakeCosmeticSkinReq; res: ISnakeCosmeticProfileRes };
    "user.getUserId": { req: IGetUserIdReq; res: IGetUserIdRes };
    "user.getInfo": { req: IGetInfoReq; res: IGetInfoRes };
    "user.getProfile": { req: IGetProfileReq; res: IGetProfileRes };
    "user.updateProfile": { req: IUpdateProfileReq; res: IUpdateProfileRes };
    "world.enter": { req: IWorldEnterReq; res: IWorldEnterRes };
    "world.resolveTransfer": { req: IWorldResolveTransferReq; res: IWorldResolveTransferRes };
}

export type LobbyRpcType = keyof LobbyRpcMap;
export type RpcReq<T extends LobbyRpcType> = LobbyRpcMap[T]["req"];
export type RpcRes<T extends LobbyRpcType> = LobbyRpcMap[T]["res"];

/** 幂等写路由子集（mode=idempotent-write 的显式字面量联合——由 metadata 生成，⛔ 非 clientReqId 结构推断） */
export type LobbyRpcIdemType =
    | "arena.capture"
    | "arenaShop.buyBoost"
    | "guild.join"
    | "guild.leave"
    | "income.claimOffline"
    | "mail.claimAttach"
    | "party.create"
    | "party.invite"
    | "party.accept"
    | "party.decline"
    | "party.leave"
    | "party.kick"
    | "party.transferLeader"
    | "redeem.claim"
    | "room.prepareCreate"
    | "shop.purchase"
    | "slg.tileCapture"
    | "slg.marchDispatch"
    | "slg.marchRecall"
    | "user.updateProfile";

/** natural-write 路由子集（写入天然可安全重复；不进通用幂等层） */
export type LobbyRpcNaturalWriteType =
    | "chat.send"
    | "income.settleOnline"
    | "mail.markRead"
    | "slg.mapTiles"
    | "snakeCosmetic.equip"
    | "snakeCosmetic.unlock";

/** 路由 → 执行模式（服务端 defineRpc 据此派生 schema/幂等行为，endpoint 不再自填） */
export const LOBBY_RPC_ROUTE_MODES: { readonly [K in LobbyRpcType]: LobbyRpcRouteMode } = {
    "arena.board": "query",
    "arena.capture": "idempotent-write",
    "arenaShop.buyBoost": "idempotent-write",
    "chat.send": "natural-write",
    "guild.join": "idempotent-write",
    "guild.leave": "idempotent-write",
    "guild.getEvents": "query",
    "income.getPending": "query",
    "income.settleOnline": "natural-write",
    "income.claimOffline": "idempotent-write",
    "mail.list": "query",
    "mail.claimAttach": "idempotent-write",
    "mail.markRead": "natural-write",
    "party.create": "idempotent-write",
    "party.invite": "idempotent-write",
    "party.accept": "idempotent-write",
    "party.decline": "idempotent-write",
    "party.leave": "idempotent-write",
    "party.kick": "idempotent-write",
    "party.transferLeader": "idempotent-write",
    "party.get": "query",
    "party.getEvents": "query",
    "redeem.claim": "idempotent-write",
    "room.prepareCreate": "idempotent-write",
    "room.resolve": "query",
    "shop.purchase": "idempotent-write",
    "shop.queryOp": "query",
    "slg.mapTiles": "natural-write",
    "slg.tileCapture": "idempotent-write",
    "slg.marchDispatch": "idempotent-write",
    "slg.marchRecall": "idempotent-write",
    "snakeCosmetic.getSnapshot": "query",
    "snakeCosmetic.equip": "natural-write",
    "snakeCosmetic.unlock": "natural-write",
    "user.getUserId": "query",
    "user.getInfo": "query",
    "user.getProfile": "query",
    "user.updateProfile": "idempotent-write",
    "world.enter": "query",
    "world.resolveTransfer": "query",
};

/** 运行时全集：服务端 loader 启动校验 + 契约测试用。新增路由若漏在此处，服务端拒绝启动。 */
export const ALL_LOBBY_RPC_TYPES: readonly LobbyRpcType[] = [
    "arena.board",
    "arena.capture",
    "arenaShop.buyBoost",
    "chat.send",
    "guild.join",
    "guild.leave",
    "guild.getEvents",
    "income.getPending",
    "income.settleOnline",
    "income.claimOffline",
    "mail.list",
    "mail.claimAttach",
    "mail.markRead",
    "party.create",
    "party.invite",
    "party.accept",
    "party.decline",
    "party.leave",
    "party.kick",
    "party.transferLeader",
    "party.get",
    "party.getEvents",
    "redeem.claim",
    "room.prepareCreate",
    "room.resolve",
    "shop.purchase",
    "shop.queryOp",
    "slg.mapTiles",
    "slg.tileCapture",
    "slg.marchDispatch",
    "slg.marchRecall",
    "snakeCosmetic.getSnapshot",
    "snakeCosmetic.equip",
    "snakeCosmetic.unlock",
    "user.getUserId",
    "user.getInfo",
    "user.getProfile",
    "user.updateProfile",
    "world.enter",
    "world.resolveTransfer",
];

/** 路由 → 契约版本（§6.11：随 validator 语义变更人工 bump；幂等 v2 记录持久化并 fail-closed 比对，
 *  ⛔ 不进摘要 preimage、不进 Redis key）。缺省 1。 */
export const LOBBY_RPC_CONTRACT_VERSIONS: { readonly [K in LobbyRpcType]: number } = {
    "arena.board": 1,
    "arena.capture": 1,
    "arenaShop.buyBoost": 1,
    "chat.send": 1,
    "guild.join": 1,
    "guild.leave": 1,
    "guild.getEvents": 1,
    "income.getPending": 1,
    "income.settleOnline": 1,
    "income.claimOffline": 1,
    "mail.list": 1,
    "mail.claimAttach": 1,
    "mail.markRead": 1,
    "party.create": 1,
    "party.invite": 1,
    "party.accept": 1,
    "party.decline": 1,
    "party.leave": 1,
    "party.kick": 1,
    "party.transferLeader": 1,
    "party.get": 1,
    "party.getEvents": 1,
    "redeem.claim": 1,
    "room.prepareCreate": 1,
    "room.resolve": 1,
    "shop.purchase": 1,
    "shop.queryOp": 1,
    "slg.mapTiles": 1,
    "slg.tileCapture": 1,
    "slg.marchDispatch": 1,
    "slg.marchRecall": 1,
    "snakeCosmetic.getSnapshot": 1,
    "snakeCosmetic.equip": 1,
    "snakeCosmetic.unlock": 1,
    "user.getUserId": 1,
    "user.getInfo": 1,
    "user.getProfile": 1,
    "user.updateProfile": 1,
    "world.enter": 1,
    "world.resolveTransfer": 1,
};

/** 域契约身份（codegen 闸：domains/<域>.ts 的 sha256 变化必须伴随 contractVersion 递增；⛔ 不进 wire）。 */
export const LOBBY_RPC_DOMAIN_CONTRACTS: { readonly [domain: string]: { readonly contractVersion: number; readonly digest: string } } = {
    arena: { contractVersion: 5, digest: "aab6f8c8965ef6963420504a6990e5bda3a888d92bdfec06ee6b981d1d7469cb" },
    arenaShop: { contractVersion: 6, digest: "44fd4a3a5aff367dc06a4352bb977c20cf5edacbd1d90217e1bcc1966628bd3f" },
    chat: { contractVersion: 5, digest: "3f171c821824feddb819ae71834150beab752ce95d6436888c435a88e0f65d5f" },
    guild: { contractVersion: 5, digest: "005c6a6195a8c937dbafead7e4d3479391b91d0a6bf1a0641ba48c33cf1886ce" },
    income: { contractVersion: 7, digest: "b30d2190e3f60c2c321962190c33400ac1aef8c6cf023802b2033e396bbb676b" },
    mail: { contractVersion: 5, digest: "88ddc9bd181b49f01007cc4af01655845fabdd13365095e56ff776c47c208368" },
    party: { contractVersion: 5, digest: "a80b6379ef7d6242f4c035dc41c54fc5a0648bbfe9f9780974bcb86bb1279b24" },
    redeem: { contractVersion: 5, digest: "01729116448beef18e707d6fde5368354ee65643889b7f7e6749f594525c1aaa" },
    room: { contractVersion: 5, digest: "390209b1681dc83e238b1c52fdc2a3d446844b6522ea3a1a6e595bc67fa86003" },
    shop: { contractVersion: 5, digest: "68e696920a46d253a8c4e6ee27a636f3a45562085c35c70aa7a611a1f07c3e5f" },
    slg: { contractVersion: 6, digest: "83374c275d0159ffba1c4700cddf22ea548ba204ee14407cd262b89e21840064" },
    snakeCosmetic: { contractVersion: 7, digest: "138da20da633269cb11f13de65abf04041b92d851328bb6a3998383d79802f11" },
    user: { contractVersion: 5, digest: "2bdaf7c83b42005ee958d933e9e846b923c7d17176231d220133b35108d39c6f" },
    world: { contractVersion: 6, digest: "1eaea7435245ec9d128571b9dbff4aae9a356d1c70ec9e47acf2e25fdda323f5" },
};

/** idempotent-write 路由 → operation group（§6.13 inspect 机制的元数据；未声明不入表）。 */
export const LOBBY_RPC_OPERATION_GROUPS: { readonly [K in LobbyRpcType]?: string } = {
};

/** 可通用查询操作状态的路由集合（inspectable=true）。 */
export const LOBBY_RPC_INSPECTABLE: readonly LobbyRpcType[] = [
];

/** query 路由 → 其可查询的 operation group（inspectsOperationGroup）。 */
export const LOBBY_RPC_INSPECTS: { readonly [K in LobbyRpcType]?: string } = {
};

/** Route request validators: exact fields + finite/range checks, shared by client and server adapters. */
export const LOBBY_RPC_REQUEST_VALIDATORS: { readonly [K in LobbyRpcType]: RuntimeValidator<RpcReq<K>> } = {
    "arena.board": guardRpcValidator("payload", validateArenaBoardReq),
    "arena.capture": guardRpcValidator("payload", validateArenaCaptureReq),
    "arenaShop.buyBoost": guardRpcValidator("payload", validateArenaShopBuyBoostReq),
    "chat.send": guardRpcValidator("payload", validateChatSendReq),
    "guild.join": guardRpcValidator("payload", validateGuildJoinReq),
    "guild.leave": guardRpcValidator("payload", validateGuildLeaveReq),
    "guild.getEvents": guardRpcValidator("payload", validateGuildGetEventsReq),
    "income.getPending": guardRpcValidator("payload", validateIncomeGetPendingReq),
    "income.settleOnline": guardRpcValidator("payload", validateIncomeSettleOnlineReq),
    "income.claimOffline": guardRpcValidator("payload", validateIncomeClaimOfflineReq),
    "mail.list": guardRpcValidator("payload", validateMailListReq),
    "mail.claimAttach": guardRpcValidator("payload", validateMailClaimAttachReq),
    "mail.markRead": guardRpcValidator("payload", validateMailMarkReadReq),
    "party.create": guardRpcValidator("payload", validatePartyCreateReq),
    "party.invite": guardRpcValidator("payload", validatePartyInviteReq),
    "party.accept": guardRpcValidator("payload", validatePartyAcceptReq),
    "party.decline": guardRpcValidator("payload", validatePartyDeclineReq),
    "party.leave": guardRpcValidator("payload", validatePartyLeaveReq),
    "party.kick": guardRpcValidator("payload", validatePartyKickReq),
    "party.transferLeader": guardRpcValidator("payload", validatePartyTransferLeaderReq),
    "party.get": guardRpcValidator("payload", validatePartyGetReq),
    "party.getEvents": guardRpcValidator("payload", validatePartyGetEventsReq),
    "redeem.claim": guardRpcValidator("payload", validateRedeemClaimReq),
    "room.prepareCreate": guardRpcValidator("payload", validateRoomPrepareCreateReq),
    "room.resolve": guardRpcValidator("payload", validateRoomResolveReq),
    "shop.purchase": guardRpcValidator("payload", validateShopPurchaseReq),
    "shop.queryOp": guardRpcValidator("payload", validateShopQueryOpReq),
    "slg.mapTiles": guardRpcValidator("payload", validateSlgMapTilesReq),
    "slg.tileCapture": guardRpcValidator("payload", validateSlgTileCaptureReq),
    "slg.marchDispatch": guardRpcValidator("payload", validateSlgMarchDispatchReq),
    "slg.marchRecall": guardRpcValidator("payload", validateSlgMarchRecallReq),
    "snakeCosmetic.getSnapshot": guardRpcValidator("payload", validateSnakeCosmeticGetSnapshotReq),
    "snakeCosmetic.equip": guardRpcValidator("payload", validateSnakeCosmeticEquipReq),
    "snakeCosmetic.unlock": guardRpcValidator("payload", validateSnakeCosmeticUnlockReq),
    "user.getUserId": guardRpcValidator("payload", validateUserGetUserIdReq),
    "user.getInfo": guardRpcValidator("payload", validateUserGetInfoReq),
    "user.getProfile": guardRpcValidator("payload", validateUserGetProfileReq),
    "user.updateProfile": guardRpcValidator("payload", validateUserUpdateProfileReq),
    "world.enter": guardRpcValidator("payload", validateWorldEnterReq),
    "world.resolveTransfer": guardRpcValidator("payload", validateWorldResolveTransferReq),
};

/** Route response validators. */
export const LOBBY_RPC_RESPONSE_VALIDATORS: { readonly [K in LobbyRpcType]: RuntimeValidator<RpcRes<K>> } = {
    "arena.board": guardRpcValidator("response", validateArenaBoardRes),
    "arena.capture": guardRpcValidator("response", validateArenaCaptureRes),
    "arenaShop.buyBoost": guardRpcValidator("response", validateArenaShopBuyBoostRes),
    "chat.send": guardRpcValidator("response", validateChatSendRes),
    "guild.join": guardRpcValidator("response", validateGuildJoinRes),
    "guild.leave": guardRpcValidator("response", validateGuildLeaveRes),
    "guild.getEvents": guardRpcValidator("response", validateGuildGetEventsRes),
    "income.getPending": guardRpcValidator("response", validateIncomeGetPendingRes),
    "income.settleOnline": guardRpcValidator("response", validateIncomeSettleOnlineRes),
    "income.claimOffline": guardRpcValidator("response", validateIncomeClaimOfflineRes),
    "mail.list": guardRpcValidator("response", validateMailListRes),
    "mail.claimAttach": guardRpcValidator("response", validateMailClaimAttachRes),
    "mail.markRead": guardRpcValidator("response", validateMailMarkReadRes),
    "party.create": guardRpcValidator("response", validatePartyCreateRes),
    "party.invite": guardRpcValidator("response", validatePartyInviteRes),
    "party.accept": guardRpcValidator("response", validatePartyAcceptRes),
    "party.decline": guardRpcValidator("response", validatePartyDeclineRes),
    "party.leave": guardRpcValidator("response", validatePartyLeaveRes),
    "party.kick": guardRpcValidator("response", validatePartyKickRes),
    "party.transferLeader": guardRpcValidator("response", validatePartyTransferLeaderRes),
    "party.get": guardRpcValidator("response", validatePartyGetRes),
    "party.getEvents": guardRpcValidator("response", validatePartyGetEventsRes),
    "redeem.claim": guardRpcValidator("response", validateRedeemClaimRes),
    "room.prepareCreate": guardRpcValidator("response", validateRoomPrepareCreateRes),
    "room.resolve": guardRpcValidator("response", validateRoomResolveRes),
    "shop.purchase": guardRpcValidator("response", validateShopPurchaseRes),
    "shop.queryOp": guardRpcValidator("response", validateShopQueryOpRes),
    "slg.mapTiles": guardRpcValidator("response", validateSlgMapTilesRes),
    "slg.tileCapture": guardRpcValidator("response", validateSlgTileCaptureRes),
    "slg.marchDispatch": guardRpcValidator("response", validateSlgMarchDispatchRes),
    "slg.marchRecall": guardRpcValidator("response", validateSlgMarchRecallRes),
    "snakeCosmetic.getSnapshot": guardRpcValidator("response", validateSnakeCosmeticGetSnapshotRes),
    "snakeCosmetic.equip": guardRpcValidator("response", validateSnakeCosmeticEquipRes),
    "snakeCosmetic.unlock": guardRpcValidator("response", validateSnakeCosmeticUnlockRes),
    "user.getUserId": guardRpcValidator("response", validateUserGetUserIdRes),
    "user.getInfo": guardRpcValidator("response", validateUserGetInfoRes),
    "user.getProfile": guardRpcValidator("response", validateUserGetProfileRes),
    "user.updateProfile": guardRpcValidator("response", validateUserUpdateProfileRes),
    "world.enter": guardRpcValidator("response", validateWorldEnterRes),
    "world.resolveTransfer": guardRpcValidator("response", validateWorldResolveTransferRes),
};

export function validateLobbyRpcRequest<T extends LobbyRpcType>(type: T, input: unknown): RpcReq<T> {
    return guardWire("payload", () => {
        const validator = LOBBY_RPC_REQUEST_VALIDATORS[type] as RuntimeValidator<RpcReq<T>> | undefined;
        if (!validator) throw new WireValidationError("RPC_TYPE", "type");
        return validator(input);
    });
}

export function validateLobbyRpcResponse<T extends LobbyRpcType>(type: T, input: unknown): RpcRes<T> {
    return guardWire("response", () => {
        const validator = LOBBY_RPC_RESPONSE_VALIDATORS[type] as RuntimeValidator<RpcRes<T>> | undefined;
        if (!validator) throw new WireValidationError("RPC_TYPE", "type");
        return validator(input);
    });
}

/** 服务端错误码全集（core + 域聚合；顺序由 coreErrors.ts 的 RPC_ERR_CODE_ORDER 历史钉决定，
 *  未上钉的新码按「core 声明序 → 域名序 → 域内声明序」追加）。服务端 ErrCode 即此联合类型。 */
export const RPC_ERR_CODES = [
    "AUTH_REQUIRED",
    "AUTH_EPOCH_STALE",
    "ACCOUNT_BANNED",
    "RATE_LIMITED",
    "INVALID_PAYLOAD",
    "UNKNOWN_TYPE",
    "INSUFFICIENT_BALANCE",
    "BUSY",
    "STALE_FENCE",
    "IN_PROGRESS",
    "GRANTING",
    "THAWING",
    "USER_DATA_LOST",
    "ORDER_MISMATCH",
    "INTERNAL",
    "OPERATION_CONFLICT",
    "OPERATION_RESULT_EXPIRED",
    "ARENA_TILE_TAKEN",
    "ARENA_SHOP_TILE_NOT_OWNED",
    "CHAT_CHANNEL_FORBIDDEN",
    "CHAT_UNAVAILABLE",
    "PARTY_NOT_FOUND",
    "PARTY_FULL",
    "PARTY_NOT_MEMBER",
    "PARTY_NOT_LEADER",
    "PARTY_ALREADY_IN_PARTY",
    "PARTY_INVITE_INVALID",
    "PARTY_TARGET_OFFLINE",
    "REDEEM_CODE_INVALID",
    "REDEEM_CODE_USED",
    "ROOM_CODE_UNAVAILABLE",
    "ROOM_FULL",
    "ROOM_START_IN_PROGRESS",
    "ROOM_QUOTA_EXCEEDED",
    "ROOM_SERVICE_UNAVAILABLE",
    "ROOM_RESULT_UNKNOWN",
    "SLG_TILE_NOT_OWNED",
    "SLG_MARCH_LIMIT",
    "SLG_MARCH_NOT_FOUND",
    "SLG_MARCH_FINISHED",
    "SLG_SETTLEMENT_PENDING",
    "SNAKE_SKIN_UNKNOWN",
    "SNAKE_SKIN_NOT_OWNED",
    "SNAKE_SKIN_NOT_CRAFTABLE",
    "SNAKE_SKIN_FRAGMENTS_INSUFFICIENT",
    "SNAKE_COSMETIC_WRITES_DISABLED",
    "WORLD_PERSONA_INVALID",
    "WORLD_TRANSFER_INVALID",
    "WORLD_LINE_UNAVAILABLE",
    "WORLD_SERVICE_UNAVAILABLE",
] as const;

export type RpcErrCode = (typeof RPC_ERR_CODES)[number];

export function isRpcErrCode(value: unknown): value is RpcErrCode {
    return typeof value === "string" && (RPC_ERR_CODES as readonly string[]).includes(value);
}

/** 推送类型名（core + 各域 pushes 的显式字面量聚合） */
export const LobbyPush = {
    ServerNotice: "server.notice",
    ForceLogout: "auth.forceLogout",
    ChatMessage: "chat.message",
    GuildEvent: "guild.event",
    MailNew: "mail.new",
    PartyEvent: "party.event",
    PartyInvited: "party.invited",
    WorldTransfer: "world.transfer",
} as const;

/** 推送类型名 → data 形状（客户端 WebSocketClient.onPush 的类型域） */
export interface LobbyPushMap {
    "server.notice": IServerNoticePush;
    "auth.forceLogout": IForceLogoutPush;
    "chat.message": IChatMessagePush;
    "guild.event": IGuildEventPush;
    "mail.new": IMailNewPush;
    "party.event": IPartyEventPush;
    "party.invited": IPartyInvitedPush;
    "world.transfer": IWorldTransferPush;
}

export type LobbyPushType = keyof LobbyPushMap;

/** 推送 data runtime validators（与各 descriptor 引用同一函数）。 */
export const PUSH_RUNTIME_VALIDATORS: { readonly [K in LobbyPushType]: RuntimeValidator<LobbyPushMap[K]> } = {
    "server.notice": validateServerNoticePush,
    "auth.forceLogout": validateForceLogoutPush,
    "chat.message": validateChatMessagePush,
    "guild.event": validateGuildEventPush,
    "mail.new": validateMailNewPush,
    "party.event": validatePartyEventPush,
    "party.invited": validatePartyInvitedPush,
    "world.transfer": validateWorldTransferPush,
};

export function validatePushData<K extends LobbyPushType>(type: K, input: unknown): LobbyPushMap[K] {
    const validator = Object.prototype.hasOwnProperty.call(PUSH_RUNTIME_VALIDATORS, type)
        ? (PUSH_RUNTIME_VALIDATORS[type] as RuntimeValidator<LobbyPushMap[K]>)
        : undefined;
    if (!validator) throw new WireValidationError("PUSH_TYPE", "push.type");
    return validator(input);
}

/** Discriminated push envelope; narrowing `type` also narrows `data`. */
export type LobbyPushEnvelope = {
    [K in LobbyPushType]: { type: K; data: LobbyPushMap[K] };
}[LobbyPushType];

/** 主动推送 envelope（{type,data}）的 exact runtime validator。 */
export function validateLobbyPush(input: unknown): LobbyPushEnvelope {
    return guardWire("push", () => {
        const value = pushRecord(input, "push");
        assertExactKeys(value, ["type", "data"], [], "push");
        const type = value.type;
        if (type !== "server.notice"
            && type !== "auth.forceLogout"
            && type !== "chat.message"
            && type !== "guild.event"
            && type !== "mail.new"
            && type !== "party.event"
            && type !== "party.invited"
            && type !== "world.transfer") {
            throw new WireValidationError("PUSH_TYPE", "push.type");
        }
        return { type, data: validatePushData(type, value.data) } as LobbyPushEnvelope;
    });
}
