/** AUTO-GENERATED by apps/server/tools/feature-codegen/cli.ts from apps/shared/src/protocol/lobbyRpc/domains/*.ts + apps/shared/src/protocol/lobbyRpc/coreErrors.ts. Do not edit. */
import { assertExactKeys, guardWire, WireValidationError, type RuntimeValidator } from "../http";
import type { LobbyRpcRouteMode } from "./defineDomain";
import { guardRpcValidator, pushRecord } from "./primitives";
import { validateForceLogoutPush, validateServerNoticePush, type IForceLogoutPush, type IServerNoticePush } from "./coreErrors";
import type { IPurchaseResult } from "./economy";
import { validateEventsRes, validateGuildEventPush, validateGuildEventsReq, validateGuildJoinReq, validateGuildLeaveReq, validateGuildLeaveRes, validateJoinRes, type IGuildEventPush, type IGuildGetEventsReq, type IGuildGetEventsRes, type IGuildJoinReq, type IGuildJoinRes, type IGuildLeaveReq, type IGuildLeaveRes } from "./domains/guild";
import { validateMailClaimAttachRes, validateMailClaimReq, validateMailListReq, validateMailListRes, validateMailMarkReadRes, validateMailMarkReq, validateMailNewPush, type IMailClaimAttachReq, type IMailListReq, type IMailListRes, type IMailMarkReadReq, type IMailMarkReadRes, type IMailNewPush } from "./domains/mail";
import { validateRedeemClaimReq, validateRedeemClaimRes, type IRedeemClaimReq, type IRedeemClaimRes } from "./domains/redeem";
import { validatePrepareCreateReq, validatePrepareCreateRes, validateResolveReq, validateResolveRes, type IRoomPrepareCreateReq, type IRoomPrepareCreateRes, type IRoomResolveReq, type IRoomResolveRes } from "./domains/room";
import { validatePurchaseResult, validateShopPurchaseReq, validateShopQueryReq, type IShopPurchaseReq, type IShopQueryOpReq } from "./domains/shop";
import { validateGetInfoReq, validateGetInfoRes, validateGetProfileReq, validateGetUserIdReq, validateGetUserIdRes, validateProfileRes, validateUpdateProfileReq, validateUpdateRes, type IGetInfoReq, type IGetInfoRes, type IGetProfileReq, type IGetProfileRes, type IGetUserIdReq, type IGetUserIdRes, type IUpdateProfileReq, type IUpdateProfileRes } from "./domains/user";

/** 领域全集（生成器删除保护锚 + 向量 sidecar 的域集合闸）。 */
export const LOBBY_RPC_DOMAINS: readonly string[] = [
    "guild",
    "mail",
    "redeem",
    "room",
    "shop",
    "user",
];

/** 全量路由契约（服务端 defineRpc 与客户端 WebSocketClient.rpc 的公共类型域） */
export interface LobbyRpcMap {
    "guild.join": { req: IGuildJoinReq; res: IGuildJoinRes };
    "guild.leave": { req: IGuildLeaveReq; res: IGuildLeaveRes };
    "guild.getEvents": { req: IGuildGetEventsReq; res: IGuildGetEventsRes };
    "mail.list": { req: IMailListReq; res: IMailListRes };
    "mail.claimAttach": { req: IMailClaimAttachReq; res: IPurchaseResult };
    "mail.markRead": { req: IMailMarkReadReq; res: IMailMarkReadRes };
    "redeem.claim": { req: IRedeemClaimReq; res: IRedeemClaimRes };
    "room.prepareCreate": { req: IRoomPrepareCreateReq; res: IRoomPrepareCreateRes };
    "room.resolve": { req: IRoomResolveReq; res: IRoomResolveRes };
    "shop.purchase": { req: IShopPurchaseReq; res: IPurchaseResult };
    "shop.queryOp": { req: IShopQueryOpReq; res: IPurchaseResult };
    "user.getUserId": { req: IGetUserIdReq; res: IGetUserIdRes };
    "user.getInfo": { req: IGetInfoReq; res: IGetInfoRes };
    "user.getProfile": { req: IGetProfileReq; res: IGetProfileRes };
    "user.updateProfile": { req: IUpdateProfileReq; res: IUpdateProfileRes };
}

export type LobbyRpcType = keyof LobbyRpcMap;
export type RpcReq<T extends LobbyRpcType> = LobbyRpcMap[T]["req"];
export type RpcRes<T extends LobbyRpcType> = LobbyRpcMap[T]["res"];

/** 幂等写路由子集（mode=idempotent-write 的显式字面量联合——由 metadata 生成，⛔ 非 clientReqId 结构推断） */
export type LobbyRpcIdemType =
    | "guild.join"
    | "guild.leave"
    | "mail.claimAttach"
    | "redeem.claim"
    | "room.prepareCreate"
    | "shop.purchase"
    | "user.updateProfile";

/** natural-write 路由子集（写入天然可安全重复；不进通用幂等层） */
export type LobbyRpcNaturalWriteType =
    | "mail.markRead";

/** 路由 → 执行模式（服务端 defineRpc 据此派生 schema/幂等行为，endpoint 不再自填） */
export const LOBBY_RPC_ROUTE_MODES: { readonly [K in LobbyRpcType]: LobbyRpcRouteMode } = {
    "guild.join": "idempotent-write",
    "guild.leave": "idempotent-write",
    "guild.getEvents": "query",
    "mail.list": "query",
    "mail.claimAttach": "idempotent-write",
    "mail.markRead": "natural-write",
    "redeem.claim": "idempotent-write",
    "room.prepareCreate": "idempotent-write",
    "room.resolve": "query",
    "shop.purchase": "idempotent-write",
    "shop.queryOp": "query",
    "user.getUserId": "query",
    "user.getInfo": "query",
    "user.getProfile": "query",
    "user.updateProfile": "idempotent-write",
};

/** 运行时全集：服务端 loader 启动校验 + 契约测试用。新增路由若漏在此处，服务端拒绝启动。 */
export const ALL_LOBBY_RPC_TYPES: readonly LobbyRpcType[] = [
    "guild.join",
    "guild.leave",
    "guild.getEvents",
    "mail.list",
    "mail.claimAttach",
    "mail.markRead",
    "redeem.claim",
    "room.prepareCreate",
    "room.resolve",
    "shop.purchase",
    "shop.queryOp",
    "user.getUserId",
    "user.getInfo",
    "user.getProfile",
    "user.updateProfile",
];

/** 路由 → 契约版本（§6.11：随 validator 语义变更人工 bump；幂等 v2 记录持久化并 fail-closed 比对，
 *  ⛔ 不进摘要 preimage、不进 Redis key）。缺省 1。 */
export const LOBBY_RPC_CONTRACT_VERSIONS: { readonly [K in LobbyRpcType]: number } = {
    "guild.join": 1,
    "guild.leave": 1,
    "guild.getEvents": 1,
    "mail.list": 1,
    "mail.claimAttach": 1,
    "mail.markRead": 1,
    "redeem.claim": 1,
    "room.prepareCreate": 1,
    "room.resolve": 1,
    "shop.purchase": 1,
    "shop.queryOp": 1,
    "user.getUserId": 1,
    "user.getInfo": 1,
    "user.getProfile": 1,
    "user.updateProfile": 1,
};

/** 域契约身份（codegen 闸：domains/<域>.ts 的 sha256 变化必须伴随 contractVersion 递增；⛔ 不进 wire）。 */
export const LOBBY_RPC_DOMAIN_CONTRACTS: { readonly [domain: string]: { readonly contractVersion: number; readonly digest: string } } = {
    guild: { contractVersion: 1, digest: "4a996a135ffd900eb39c0b83697ee03d4d4587829da88ce537f363d56ceb4bde" },
    mail: { contractVersion: 1, digest: "d6401c80a558ce24849ad9c038bd34e2adc09bd9b006abef773cbecf409b7ab4" },
    redeem: { contractVersion: 1, digest: "e7e74dc98acf6cfb1d5bfd0261930d6bbc5bb07e2efa79dec0e91be485596514" },
    room: { contractVersion: 1, digest: "8655531a80f2ffc6a941247c2c2ef00ad44dfb3842b722741556430bf2c12ff2" },
    shop: { contractVersion: 1, digest: "80f5bc9c74300aecd0bf2caf8dea93506657c5e9a4d64e91931760e8c06544cf" },
    user: { contractVersion: 1, digest: "ce1f3ff0528a15836c188d111ddbe29bfb8c97c4f68d69c3e77a9432fe157a28" },
};

/** idempotent-write 路由 → operation group（§6.13 inspect 机制的元数据；未声明不入表）。 */
export const LOBBY_RPC_OPERATION_GROUPS: { readonly [K in LobbyRpcType]?: string } = {
};

/** 可通用查询操作状态的路由集合（inspectable=true）。 */
export const LOBBY_RPC_INSPECTABLE: readonly LobbyRpcType[] = [
];

/** query 路由 → 其可查询的 operation group（inspectsOperationGroup）。 */
export const LOBBY_RPC_INSPECTS: { readonly [K in LobbyRpcType]?: string } = {
};

/** Route request validators: exact fields + finite/range checks, shared by client and server adapters. */
export const LOBBY_RPC_REQUEST_VALIDATORS: { readonly [K in LobbyRpcType]: RuntimeValidator<RpcReq<K>> } = {
    "guild.join": guardRpcValidator("payload", validateGuildJoinReq),
    "guild.leave": guardRpcValidator("payload", validateGuildLeaveReq),
    "guild.getEvents": guardRpcValidator("payload", validateGuildEventsReq),
    "mail.list": guardRpcValidator("payload", validateMailListReq),
    "mail.claimAttach": guardRpcValidator("payload", validateMailClaimReq),
    "mail.markRead": guardRpcValidator("payload", validateMailMarkReq),
    "redeem.claim": guardRpcValidator("payload", validateRedeemClaimReq),
    "room.prepareCreate": guardRpcValidator("payload", validatePrepareCreateReq),
    "room.resolve": guardRpcValidator("payload", validateResolveReq),
    "shop.purchase": guardRpcValidator("payload", validateShopPurchaseReq),
    "shop.queryOp": guardRpcValidator("payload", validateShopQueryReq),
    "user.getUserId": guardRpcValidator("payload", validateGetUserIdReq),
    "user.getInfo": guardRpcValidator("payload", validateGetInfoReq),
    "user.getProfile": guardRpcValidator("payload", validateGetProfileReq),
    "user.updateProfile": guardRpcValidator("payload", validateUpdateProfileReq),
};

/** Route response validators. */
export const LOBBY_RPC_RESPONSE_VALIDATORS: { readonly [K in LobbyRpcType]: RuntimeValidator<RpcRes<K>> } = {
    "guild.join": guardRpcValidator("response", validateJoinRes),
    "guild.leave": guardRpcValidator("response", validateGuildLeaveRes),
    "guild.getEvents": guardRpcValidator("response", validateEventsRes),
    "mail.list": guardRpcValidator("response", validateMailListRes),
    "mail.claimAttach": guardRpcValidator("response", validateMailClaimAttachRes),
    "mail.markRead": guardRpcValidator("response", validateMailMarkReadRes),
    "redeem.claim": guardRpcValidator("response", validateRedeemClaimRes),
    "room.prepareCreate": guardRpcValidator("response", validatePrepareCreateRes),
    "room.resolve": guardRpcValidator("response", validateResolveRes),
    "shop.purchase": guardRpcValidator("response", validatePurchaseResult),
    "shop.queryOp": guardRpcValidator("response", validatePurchaseResult),
    "user.getUserId": guardRpcValidator("response", validateGetUserIdRes),
    "user.getInfo": guardRpcValidator("response", validateGetInfoRes),
    "user.getProfile": guardRpcValidator("response", validateProfileRes),
    "user.updateProfile": guardRpcValidator("response", validateUpdateRes),
};

export function validateLobbyRpcRequest<T extends LobbyRpcType>(type: T, input: unknown): RpcReq<T> {
    return guardWire("payload", () => {
        const validator = LOBBY_RPC_REQUEST_VALIDATORS[type] as RuntimeValidator<RpcReq<T>> | undefined;
        if (!validator) throw new WireValidationError("RPC_TYPE", "type");
        return validator(input);
    });
}

export function validateLobbyRpcResponse<T extends LobbyRpcType>(type: T, input: unknown): RpcRes<T> {
    return guardWire("response", () => {
        const validator = LOBBY_RPC_RESPONSE_VALIDATORS[type] as RuntimeValidator<RpcRes<T>> | undefined;
        if (!validator) throw new WireValidationError("RPC_TYPE", "type");
        return validator(input);
    });
}

/** 服务端错误码全集（core + 域聚合；顺序由 coreErrors.ts 的 RPC_ERR_CODE_ORDER 历史钉决定，
 *  未上钉的新码按「core 声明序 → 域名序 → 域内声明序」追加）。服务端 ErrCode 即此联合类型。 */
export const RPC_ERR_CODES = [
    "AUTH_REQUIRED",
    "AUTH_EPOCH_STALE",
    "ACCOUNT_BANNED",
    "RATE_LIMITED",
    "INVALID_PAYLOAD",
    "UNKNOWN_TYPE",
    "INSUFFICIENT_BALANCE",
    "BUSY",
    "STALE_FENCE",
    "IN_PROGRESS",
    "GRANTING",
    "THAWING",
    "USER_DATA_LOST",
    "ORDER_MISMATCH",
    "INTERNAL",
    "OPERATION_CONFLICT",
    "OPERATION_RESULT_EXPIRED",
    "REDEEM_CODE_INVALID",
    "REDEEM_CODE_USED",
    "ROOM_CODE_UNAVAILABLE",
    "ROOM_FULL",
    "ROOM_START_IN_PROGRESS",
    "ROOM_QUOTA_EXCEEDED",
    "ROOM_SERVICE_UNAVAILABLE",
    "ROOM_RESULT_UNKNOWN",
] as const;

export type RpcErrCode = (typeof RPC_ERR_CODES)[number];

export function isRpcErrCode(value: unknown): value is RpcErrCode {
    return typeof value === "string" && (RPC_ERR_CODES as readonly string[]).includes(value);
}

/** 推送类型名（core + 各域 pushes 的显式字面量聚合） */
export const LobbyPush = {
    ServerNotice: "server.notice",
    ForceLogout: "auth.forceLogout",
    GuildEvent: "guild.event",
    MailNew: "mail.new",
} as const;

/** 推送类型名 → data 形状（客户端 WebSocketClient.onPush 的类型域） */
export interface LobbyPushMap {
    "server.notice": IServerNoticePush;
    "auth.forceLogout": IForceLogoutPush;
    "guild.event": IGuildEventPush;
    "mail.new": IMailNewPush;
}

export type LobbyPushType = keyof LobbyPushMap;

/** 推送 data runtime validators（与各 descriptor 引用同一函数）。 */
export const PUSH_RUNTIME_VALIDATORS: { readonly [K in LobbyPushType]: RuntimeValidator<LobbyPushMap[K]> } = {
    "server.notice": validateServerNoticePush,
    "auth.forceLogout": validateForceLogoutPush,
    "guild.event": validateGuildEventPush,
    "mail.new": validateMailNewPush,
};

export function validatePushData<K extends LobbyPushType>(type: K, input: unknown): LobbyPushMap[K] {
    const validator = Object.prototype.hasOwnProperty.call(PUSH_RUNTIME_VALIDATORS, type)
        ? (PUSH_RUNTIME_VALIDATORS[type] as RuntimeValidator<LobbyPushMap[K]>)
        : undefined;
    if (!validator) throw new WireValidationError("PUSH_TYPE", "push.type");
    return validator(input);
}

/** Discriminated push envelope; narrowing `type` also narrows `data`. */
export type LobbyPushEnvelope = {
    [K in LobbyPushType]: { type: K; data: LobbyPushMap[K] };
}[LobbyPushType];

/** 主动推送 envelope（{type,data}）的 exact runtime validator。 */
export function validateLobbyPush(input: unknown): LobbyPushEnvelope {
    return guardWire("push", () => {
        const value = pushRecord(input, "push");
        assertExactKeys(value, ["type", "data"], [], "push");
        const type = value.type;
        if (type !== "server.notice"
            && type !== "auth.forceLogout"
            && type !== "guild.event"
            && type !== "mail.new") {
            throw new WireValidationError("PUSH_TYPE", "push.type");
        }
        return { type, data: validatePushData(type, value.data) } as LobbyPushEnvelope;
    });
}
