/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json}. Do not edit. */
import { WireValidationError } from "../protocol/http";
import { validateGameRoomState, type IGameRoomState } from "./generated/state/ballMove";
import { validateIdleRoomState, type IIdleRoomState } from "./generated/state/idle";

/** Wire root interfaces keyed by canonical gameplay mode id. */
export interface RoomStateByMode {
    "ballMove": IGameRoomState;
    "idle": IIdleRoomState;
}

export type RoomStateMode = keyof RoomStateByMode;
export type RoomState = RoomStateByMode[RoomStateMode];
export type RoomStateValidator<M extends RoomStateMode> = (input: unknown) => RoomStateByMode[M];

export const ROOM_STATE_VALIDATORS = Object.freeze({
    "ballMove": validateGameRoomState,
    "idle": validateIdleRoomState,
} as const satisfies { readonly [M in RoomStateMode]: RoomStateValidator<M> });

export function validateRoomStateForMode<M extends RoomStateMode>(mode: M, input: unknown): RoomStateByMode[M];
export function validateRoomStateForMode(mode: string, input: unknown): RoomState;
export function validateRoomStateForMode(mode: string, input: unknown): RoomState {
    const validator = (ROOM_STATE_VALIDATORS as Readonly<Partial<Record<string, (value: unknown) => RoomState>>>)[mode];
    if (!validator) throw new WireValidationError("STATE_MODE", "mode");
    return validator(input);
}

/** Per-gameplay catalog. contractDigest = sha256(manifest.json + "\0" + state.json + "\0" + wire.ts). */
export const GAMEPLAY_CATALOG = {
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 2,
        maxPlayers: 4,
        contractDigest: "666bb0389fa4167a2208fee2b7f415ae2ef4fb0c6604e9b6924664716929c2a2",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 2,
        maxPlayers: 4,
        contractDigest: "9151b3a0e1913f7ac53c77cad3dd8b72a719e0ce335524e188e248b6fdece695",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;
