/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json}. Do not edit. */
import { WireValidationError } from "../protocol/http";
import { validateGameRoomState, type IGameRoomState } from "./generated/state/ballMove";
import { validateDropInFixtureState, type IDropInFixtureState } from "./generated/state/dropInFixture";
import { validateIdleRoomState, type IIdleRoomState } from "./generated/state/idle";
import { validatePrivateFixtureState, type IPrivateFixtureState } from "./generated/state/privateFixture";
import { validateSnakeRoomState, type ISnakeRoomState } from "./generated/state/snake";

/** Wire root interfaces keyed by canonical gameplay mode id. */
export interface RoomStateByMode {
    "ballMove": IGameRoomState;
    "dropInFixture": IDropInFixtureState;
    "idle": IIdleRoomState;
    "privateFixture": IPrivateFixtureState;
    "snake": ISnakeRoomState;
}

export type RoomStateMode = keyof RoomStateByMode;
export type RoomState = RoomStateByMode[RoomStateMode];
export type RoomStateValidator<M extends RoomStateMode> = (input: unknown) => RoomStateByMode[M];

export const ROOM_STATE_VALIDATORS = Object.freeze({
    "ballMove": validateGameRoomState,
    "dropInFixture": validateDropInFixtureState,
    "idle": validateIdleRoomState,
    "privateFixture": validatePrivateFixtureState,
    "snake": validateSnakeRoomState,
} as const satisfies { readonly [M in RoomStateMode]: RoomStateValidator<M> });

export function validateRoomStateForMode<M extends RoomStateMode>(mode: M, input: unknown): RoomStateByMode[M];
export function validateRoomStateForMode(mode: string, input: unknown): RoomState;
export function validateRoomStateForMode(mode: string, input: unknown): RoomState {
    const validator = (ROOM_STATE_VALIDATORS as Readonly<Partial<Record<string, (value: unknown) => RoomState>>>)[mode];
    if (!validator) throw new WireValidationError("STATE_MODE", "mode");
    return validator(input);
}

/** Per-gameplay catalog. contractDigest = sha256(manifest.json + "\0" + state.json + "\0" + wire.ts). */
export const GAMEPLAY_CATALOG = {
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "c8fca655408e3bae34c9b3072681536e03b9258bdc97d827015ccf19feea677e",
    },
    "dropInFixture": {
        id: "dropInFixture",
        constantName: "DropInFixture",
        modeVersion: 2,
        maxPlayers: 8,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "af9fcc0be748fbed155af39397601af6a6364a5994eb9ac90dbb1d0d02dbb2fb",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "0ecdaaa95a97d83b73df2a3f3d5535f0e4bf113fb50fa64c52a79477f0749ef7",
    },
    "privateFixture": {
        id: "privateFixture",
        constantName: "PrivateFixture",
        modeVersion: 2,
        maxPlayers: 4,
        profiles: ["default", "private"],
        stateFragments: ["ownerReady", "inviteRoom"],
        contractDigest: "d1df12c9dcfdbecd1ff5f6363876335efae1bb4a75c2123d037a4319d6130c8d",
    },
    "snake": {
        id: "snake",
        constantName: "Snake",
        modeVersion: 4,
        maxPlayers: 8,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "bb7e7c3b5a9dbabc341510e85bddd48794e39fab57935cfb88e45050f7b4b2d8",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;
