/** AUTO-GENERATED by apps/server/tools/plugin-codegen/cli.ts from apps/shared/src/protocol/lobbyRpc/domains/*.ts + apps/server/test/lobbyRpcVectors/<域>.ts. Do not edit. */
import arenaVectors from "./arena";
import arenaShopVectors from "./arenaShop";
import chatVectors from "./chat";
import guildVectors from "./guild";
import mailVectors from "./mail";
import mmoVectors from "./mmo";
import mmoSocialVectors from "./mmoSocial";
import partyVectors from "./party";
import redeemVectors from "./redeem";
import roomVectors from "./room";
import shopVectors from "./shop";
import slgVectors from "./slg";
import snakeCosmeticVectors from "./snakeCosmetic";
import userVectors from "./user";
import worldVectors from "./world";
import type { LobbyRpcVectorFile } from "./vectorTypes";

/** 域 → sidecar default（= LOBBY_RPC_DOMAINS；新增域只新增 lobbyRpcVectors/<域>.ts 并重跑 codegen:plugins）。 */
export const LOBBY_RPC_VECTOR_FILES: Readonly<Record<string, LobbyRpcVectorFile>> = {
    arena: arenaVectors,
    arenaShop: arenaShopVectors,
    chat: chatVectors,
    guild: guildVectors,
    mail: mailVectors,
    mmo: mmoVectors,
    mmoSocial: mmoSocialVectors,
    party: partyVectors,
    redeem: redeemVectors,
    room: roomVectors,
    shop: shopVectors,
    slg: slgVectors,
    snakeCosmetic: snakeCosmeticVectors,
    user: userVectors,
    world: worldVectors,
};
