/** AUTO-GENERATED by apps/server/tools/feature-codegen/cli.ts from apps/shared/src/protocol/lobbyRpc/domains/*.ts + apps/server/test/lobbyRpcVectors/<域>.ts. Do not edit. */
import guildVectors from "./guild";
import mailVectors from "./mail";
import roomVectors from "./room";
import shopVectors from "./shop";
import userVectors from "./user";
import type { LobbyRpcVectorFile } from "./vectorTypes";

/** 域 → sidecar default（= LOBBY_RPC_DOMAINS；新增域只新增 lobbyRpcVectors/<域>.ts 并重跑 codegen:features）。 */
export const LOBBY_RPC_VECTOR_FILES: Readonly<Record<string, LobbyRpcVectorFile>> = {
    guild: guildVectors,
    mail: mailVectors,
    room: roomVectors,
    shop: shopVectors,
    user: userVectors,
};
