/** Native-only discovery and generation. Never writes legacy server files. */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { parseDomainModule } from "./descriptor";

export const kitRoot = "apps/serverNew/kits";
export const protocolRoot = "apps/shared/src/native/lobbyRpc";
export function manifests(root: string): any[] {
  const dir = path.join(root, kitRoot);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((e) => {
      if (!/^[a-z][a-zA-Z0-9]*$/.test(e.name))
        throw Error("Invalid native kit directory");
      const m = JSON.parse(
        fs.readFileSync(path.join(dir, e.name, "kit.json"), "utf8"),
      );
      validateManifest(m, e.name);
      return m;
    });
}
export function validateManifest(m: any, id: string): void {
  if (
    m.id !== id ||
    m.schemaVersion !== 1 ||
    m.serverRuntime !== "serverNew" ||
    !/^\d+\.\d+\.\d+$/.test(m.version) ||
    !Array.isArray(m.domains) ||
    m.domains.some(
      (d: unknown) =>
        typeof d !== "string" ||
        !d.startsWith(m.id) ||
        !/^[a-z][a-zA-Z0-9]*$/.test(d),
    )
  )
    throw Error("Invalid native kit manifest " + id);
  for (const key of [
    "modes",
    "sql",
    "userKeys",
    "workers",
    "effects",
    "fragments",
    "contributions",
  ])
    if (m[key] !== undefined)
      throw Error("Unsupported native contribution " + key);
  for (const p of [...(m.viewDirs ?? []), ...(m.views ?? []), m.entry])
    if (
      typeof p !== "string" ||
      !p.startsWith(`apps/client/src/kits/${m.id}/`) ||
      p.includes("\\") ||
      p.split("/").some((x: string) => !x || x === "." || x === "..")
    )
      throw Error("Native client ownership violation");
  if (
    !Array.isArray(m.views) ||
    !Array.isArray(m.viewDirs) ||
    !Array.isArray(m.routes) ||
    !Array.isArray(m.menu)
  )
    throw Error("Missing native client declarations");
  const unique = (v: string[]) => new Set(v).size === v.length;
  if (
    !unique(m.domains) ||
    !unique(m.views) ||
    !unique(m.routes.map((r: any) => r.id))
  )
    throw Error("Duplicate native declarations");
}
const header =
  "/** AUTO-GENERATED by apps/serverNew/tools/kit/generate.ts. Do not edit. */\n";
export function generate(root: string, check = false): void {
  const outputs = new Map<string, string>();
  const kits = manifests(root);
  const domains: (ReturnType<typeof parseDomainModule> & { digest: string })[] =
    kits.flatMap((m) =>
      m.domains.map((name: string) => {
        const file = `${protocolRoot}/domains/${name}.ts`;
        const source = fs.readFileSync(path.join(root, file), "utf8");
        const d = parseDomainModule(source, file);
        if (d.domain !== name) throw Error("Domain identity mismatch");
        return {
          ...d,
          digest: crypto.createHash("sha256").update(source).digest("hex"),
        };
      }),
    );
  const actual = fs.existsSync(path.join(root, protocolRoot, "domains"))
    ? fs
        .readdirSync(path.join(root, protocolRoot, "domains"))
        .filter((f) => f.endsWith(".ts"))
        .map((f) => f.slice(0, -3))
        .sort()
    : [];
  if (
    JSON.stringify(actual) !==
    JSON.stringify(domains.map((d) => d.domain).sort())
  )
    throw Error("Native domains must match installed manifests exactly");
  const unique = (values: string[], label: string) => {
    if (new Set(values).size !== values.length)
      throw Error("Duplicate " + label);
  };
  unique(
    domains.map((d) => d.domain),
    "native domain",
  );
  unique(
    domains.flatMap((d) => d.routes.map((r) => r.type)),
    "native route",
  );
  unique(
    domains.flatMap((d) => d.pushes.map((p) => p.type)),
    "native push",
  );
  unique(
    domains.flatMap((d) => d.pushes.map((p) => p.key)),
    "native push key",
  );
  const legacyText = fs.readFileSync(
    path.join(root, "apps/shared/src/protocol/lobbyRpc/registry.generated.ts"),
    "utf8",
  );
  for (const d of domains)
    for (const route of d.routes)
      if (legacyText.includes(`"${route.type}"`))
        throw Error("Native route collides with legacy route");
  for (const d of domains)
    for (const p of d.pushes)
      if (
        legacyText.includes(`"${p.type}"`) ||
        new RegExp(`\\b${p.key}\\s*:`).test(legacyText)
      )
        throw Error("Native push collides with legacy push");
  let s =
    header +
    `import * as Legacy from '../../protocol/lobbyRpc/registry.generated';\nimport { assertExactKeys, guardWire, WireValidationError, type RuntimeValidator } from '../../protocol/http';\nimport { pushRecord, guardRpcValidator } from '../../protocol/lobbyRpc/primitives';\nimport type { LobbyRpcRouteMode } from '../../protocol/lobbyRpc/defineDomain';\n`;
  for (const d of domains)
    s += `import * as D_${d.domain} from './domains/${d.domain}';\nexport * from './domains/${d.domain}';\n`;
  s += "export interface LobbyRpcMap extends Legacy.LobbyRpcMap {\n";
  for (const d of domains)
    for (const r of d.routes)
      s += `${JSON.stringify(r.type)}: {req: ReturnType<typeof D_${d.domain}.${r.requestValidator}>; res: ReturnType<typeof D_${d.domain}.${r.responseValidator}>};\n`;
  s += `}\nexport type LobbyRpcType=keyof LobbyRpcMap;\nexport type RpcReq<T extends LobbyRpcType>=LobbyRpcMap[T]['req'];\nexport type RpcRes<T extends LobbyRpcType>=LobbyRpcMap[T]['res'];\n`;
  for (const [type, mode] of [
    ["LobbyRpcIdemType", "idempotent-write"],
    ["LobbyRpcNaturalWriteType", "natural-write"],
  ])
    s += `export type ${type}=Legacy.${type}${domains.flatMap((d) => d.routes.filter((r) => r.mode === mode).map((r) => " | " + JSON.stringify(r.type))).join("")};\n`;
  s += `export const ALL_LOBBY_RPC_TYPES:readonly LobbyRpcType[]=[...Legacy.ALL_LOBBY_RPC_TYPES,${domains.flatMap((d) => d.routes.map((r) => JSON.stringify(r.type))).join(",")}];\nexport const LOBBY_RPC_DOMAINS=[...Legacy.LOBBY_RPC_DOMAINS,${domains.map((d) => JSON.stringify(d.domain)).join(",")}];\n`;
  const tables: [string, string, (r: any, d: any) => string][] = [
    [
      "LOBBY_RPC_ROUTE_MODES",
      "{readonly[K in LobbyRpcType]:LobbyRpcRouteMode}",
      (r) => JSON.stringify(r.mode),
    ],
    [
      "LOBBY_RPC_CONTRACT_VERSIONS",
      "{readonly[K in LobbyRpcType]:number}",
      (r) => String(r.contractVersion),
    ],
    [
      "LOBBY_RPC_REQUEST_VALIDATORS",
      "{readonly[K in LobbyRpcType]:RuntimeValidator<RpcReq<K>>}",
      (r, d) =>
        `guardRpcValidator('payload',D_${d.domain}.${r.requestValidator})`,
    ],
    [
      "LOBBY_RPC_RESPONSE_VALIDATORS",
      "{readonly[K in LobbyRpcType]:RuntimeValidator<RpcRes<K>>}",
      (r, d) =>
        `guardRpcValidator('response',D_${d.domain}.${r.responseValidator})`,
    ],
  ];
  for (const [name, type, render] of tables)
    s += `export const ${name}:${type}={...Legacy.${name},\n${domains.flatMap((d) => d.routes.map((r) => `${JSON.stringify(r.type)}:${render(r, d)},`)).join("\n")}\n};\n`;
  for (const [suffix, field] of [
    ["OPERATION_GROUPS", "operationGroup"],
    ["INSPECTS", "inspectsOperationGroup"],
  ])
    s += `export const LOBBY_RPC_${suffix}:{readonly[K in LobbyRpcType]?:string}={...Legacy.LOBBY_RPC_${suffix},${domains.flatMap((d) => d.routes.filter((r) => (r as any)[field]).map((r) => `${JSON.stringify(r.type)}:${JSON.stringify((r as any)[field])}`)).join(",")}};\n`;
  s += `export const LOBBY_RPC_INSPECTABLE:readonly LobbyRpcType[]=[...Legacy.LOBBY_RPC_INSPECTABLE,${domains.flatMap((d) => d.routes.filter((r) => r.inspectable).map((r) => JSON.stringify(r.type))).join(",")}];\n`;
  s += `export const LOBBY_RPC_DOMAIN_CONTRACTS={...Legacy.LOBBY_RPC_DOMAIN_CONTRACTS,${domains.map((d) => `${JSON.stringify(d.domain)}:{contractVersion:${d.contractVersion},digest:${JSON.stringify(d.digest)}}`).join(",")}};\n`;
  for (const [name, table, result] of [
    ["Request", "REQUEST", "RpcReq"],
    ["Response", "RESPONSE", "RpcRes"],
  ])
    s += `export function validateLobbyRpc${name}<T extends LobbyRpcType>(type:T,input:unknown):${result}<T>{const v=Object.prototype.hasOwnProperty.call(LOBBY_RPC_${table}_VALIDATORS,type)?LOBBY_RPC_${table}_VALIDATORS[type] as RuntimeValidator<${result}<T>>:undefined;if(!v)throw new WireValidationError('RPC_TYPE','type');return v(input);}\n`;
  s += `export const RPC_ERR_CODES=[...Legacy.RPC_ERR_CODES,${[...new Set(domains.flatMap((d) => d.errorCodes))].map((x) => JSON.stringify(x)).join(",")}] as const;\nexport type RpcErrCode=typeof RPC_ERR_CODES[number];\nexport function isRpcErrCode(v:unknown):v is RpcErrCode{return typeof v==='string'&&(RPC_ERR_CODES as readonly string[]).includes(v);}\n`;
  s += `export const LobbyPush={...Legacy.LobbyPush,${domains.flatMap((d) => d.pushes.map((p) => `${p.key}:${JSON.stringify(p.type)}`)).join(",")}} as const;\nexport interface LobbyPushMap extends Legacy.LobbyPushMap {${domains.flatMap((d) => d.pushes.map((p) => `${JSON.stringify(p.type)}:ReturnType<typeof D_${d.domain}.${p.validator}>;`)).join("\n")}}\nexport type LobbyPushType=keyof LobbyPushMap;\n`;
  s += `export const PUSH_RUNTIME_VALIDATORS:{readonly[K in LobbyPushType]:RuntimeValidator<LobbyPushMap[K]>}={...Legacy.PUSH_RUNTIME_VALIDATORS,${domains.flatMap((d) => d.pushes.map((p) => `${JSON.stringify(p.type)}:D_${d.domain}.${p.validator}`)).join(",")}};\nexport type LobbyPushEnvelope={[K in LobbyPushType]:{type:K;data:LobbyPushMap[K]}}[LobbyPushType];\nexport function validatePushData<K extends LobbyPushType>(type:K,input:unknown):LobbyPushMap[K]{const v=Object.prototype.hasOwnProperty.call(PUSH_RUNTIME_VALIDATORS,type)?PUSH_RUNTIME_VALIDATORS[type] as RuntimeValidator<LobbyPushMap[K]>:undefined;if(!v)throw new WireValidationError('PUSH_TYPE','push.type');return v(input);}\nexport function validateLobbyPush(input:unknown):LobbyPushEnvelope{return guardWire('push',()=>{const v=pushRecord(input,'push');assertExactKeys(v,['type','data'],[],'push');if(typeof v.type!=='string')throw new WireValidationError('PUSH_TYPE','push.type');const type=v.type as LobbyPushType;return {type,data:validatePushData(type,v.data)} as LobbyPushEnvelope;});}\n`;
  outputs.set(`${protocolRoot}/registry.generated.ts`, s);
  // Same wire codec source, linked to the native registry. Never maintain a second handwritten codec.
  for (const name of ["index", "envelope", "transport", "push"]) {
    const src = `apps/shared/src/protocol/lobbyRpc/${name}.ts`;
    let text = fs.readFileSync(path.join(root, src), "utf8");
    text = text.replace(
      /(from\s+["'])([^"']+)(["'])/g,
      (_all, start, spec, end) => {
        if (!spec.startsWith(".")) return start + spec + end;
        const target = path.posix.normalize(
          path.posix.join(path.posix.dirname(src), spec),
        );
        const base = path.posix.basename(target);
        if (
          path.posix.dirname(target) === "apps/shared/src/protocol/lobbyRpc" &&
          [
            "index",
            "envelope",
            "transport",
            "push",
            "registry.generated",
          ].includes(base)
        )
          return (
            start +
            "./" +
            (base === "registry.generated" ? base : base + ".generated") +
            end
          );
        let rel = path.posix.relative(protocolRoot, target);
        if (!rel.startsWith(".")) rel = "./" + rel;
        return start + rel + end;
      },
    );
    outputs.set(`${protocolRoot}/${name}.generated.ts`, header + text);
  }
  outputs.set(
    "apps/shared/src/native/index.ts",
    header +
      `export * from '../index';\n` +
      [
        "LobbyRpcMap",
        "LobbyRpcType",
        "RpcReq",
        "RpcRes",
        "LobbyRpcIdemType",
        "LobbyRpcNaturalWriteType",
        "ALL_LOBBY_RPC_TYPES",
        "LOBBY_RPC_DOMAINS",
        "LOBBY_RPC_ROUTE_MODES",
        "LOBBY_RPC_CONTRACT_VERSIONS",
        "LOBBY_RPC_DOMAIN_CONTRACTS",
        "LOBBY_RPC_OPERATION_GROUPS",
        "LOBBY_RPC_INSPECTABLE",
        "LOBBY_RPC_INSPECTS",
        "LOBBY_RPC_REQUEST_VALIDATORS",
        "LOBBY_RPC_RESPONSE_VALIDATORS",
        "validateLobbyRpcRequest",
        "validateLobbyRpcResponse",
        "RPC_ERR_CODES",
        "RpcErrCode",
        "isRpcErrCode",
        "LobbyPush",
        "LobbyPushMap",
        "LobbyPushType",
        "LobbyPushEnvelope",
        "PUSH_RUNTIME_VALIDATORS",
        "validateLobbyPush",
        "validatePushData",
      ]
        .map(
          (n) =>
            `export {${["LobbyRpcMap", "LobbyRpcType", "RpcReq", "RpcRes", "LobbyRpcIdemType", "LobbyRpcNaturalWriteType", "RpcErrCode", "LobbyPushMap", "LobbyPushType", "LobbyPushEnvelope"].includes(n) ? "type " : ""}${n}} from './lobbyRpc/registry.generated';`,
        )
        .join("\n") +
      `\nexport {validateRpcReply,isValidRpcReply,type IRpcReply,type IRpcErrorReply} from './lobbyRpc/envelope.generated';\nexport {${[...fs.readFileSync(path.join(root, "apps/shared/src/protocol/lobbyRpc/transport.ts"), "utf8").matchAll(/export (const|function|interface|type) (\w+)/g)].map((m) => (["interface", "type"].includes(m[1]) ? "type " : "") + m[2]).join(",")}} from './lobbyRpc/transport.generated';\n`,
  );
  outputs.set(
    "apps/shared/src/native/kits.generated.ts",
    header +
      'export const KIT_CATALOG:readonly {id:string;version:string;serverRuntime:"serverNew";domains:readonly string[]}[]=' +
      JSON.stringify(
        kits.map((m) => ({
          id: m.id,
          version: m.version,
          serverRuntime: m.serverRuntime,
          domains: m.domains,
        })),
      ) +
      " as const;\n",
  );
  // Client catalogs have separate ownership; shared frontend merging rejects collisions.
  let client =
    header +
    `import type {GeneratedPluginDescriptor} from '../../generated/plugins.generated';\nimport type {ViewMeta} from '../../view/defineView';\nexport const NATIVE_PLUGINS:readonly GeneratedPluginDescriptor[]=[\n`;
  const viewEntries: string[] = [];
  for (const m of kits) {
    const views = new Map<string, any>();
    for (const file of m.views ?? []) {
      const v = JSON.parse(fs.readFileSync(path.join(root, file), "utf8"));
      const name = path.basename(file, ".view.json").replace(/View$/, "");
      if (v.owner !== m.id || v.kind !== "cocos")
        throw Error("Native view must be owned Cocos view");
      views.set(name, v);
      const source = file.replace(/\.view.json$/, ".ts");
      const importPath =
        "../../" + source.replace("apps/client/src/", "").replace(/\.ts$/, "");
      const { schemaVersion, owner, logic, group, restore, ...meta } = v;
      viewEntries.push(
        `${JSON.stringify(name)}:{name:${JSON.stringify(name)},${Object.entries(
          meta,
        )
          .map(([k, val]) => `${k}:${JSON.stringify(val)}`)
          .join(
            ",",
          )},load:()=>import(${JSON.stringify(importPath)}).then(m=>m.${name}View)}`,
      );
    }
    const routes = (m.routes ?? []).map((r: any) => {
      const v = views.get(r.view);
      if (!v) throw Error("Native route missing view");
      return { ...r, group: v.group, restore: v.restore };
    });
    const entry =
      "../../" + m.entry.replace("apps/client/src/", "").replace(/\.ts$/, "");
    client += `{id:${JSON.stringify(m.id)},resident:${!!m.resident},dependencies:[],routes:${JSON.stringify(routes)},menu:${JSON.stringify((m.menu ?? []).map((e: any) => ({ ...e, pluginId: m.id })))},load:()=>import(${JSON.stringify(entry)}).then(m=>m.createPluginModule())},\n`;
  }
  client += `];\nexport const NATIVE_VIEWS:Readonly<Record<string,ViewMeta>>={${viewEntries.join(",\n")}};\n`;
  outputs.set("apps/client/src/native/generated/kits.ts", client);
  // Validate every output before writing any: symlinks must not redirect native generation into another owner.
  for (const file of outputs.keys()) {
    let current = root;
    for (const part of file.split("/")) {
      current = path.join(current, part);
      if (fs.existsSync(current) && fs.lstatSync(current).isSymbolicLink())
        throw Error("Symlink native output rejected: " + file);
    }
  }
  for (const [file, text] of outputs) {
    const dest = path.join(root, file);
    if (check) {
      if (!fs.existsSync(dest) || fs.readFileSync(dest, "utf8") !== text)
        throw Error("Stale native generated file: " + file);
    } else {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      if (!fs.existsSync(dest) || fs.readFileSync(dest, "utf8") !== text)
        fs.writeFileSync(dest, text);
    }
  }
}
