/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json}. Do not edit. */
import { WireValidationError } from "../protocol/http";
import { validateGameRoomState, type IGameRoomState } from "./generated/state/ballMove";
import { validateDropInFixtureState, type IDropInFixtureState } from "./generated/state/dropInFixture";
import { validateIdleRoomState, type IIdleRoomState } from "./generated/state/idle";
import { validatePrivateFixtureState, type IPrivateFixtureState } from "./generated/state/privateFixture";

/** Wire root interfaces keyed by canonical gameplay mode id. */
export interface RoomStateByMode {
    "ballMove": IGameRoomState;
    "dropInFixture": IDropInFixtureState;
    "idle": IIdleRoomState;
    "privateFixture": IPrivateFixtureState;
}

export type RoomStateMode = keyof RoomStateByMode;
export type RoomState = RoomStateByMode[RoomStateMode];
export type RoomStateValidator<M extends RoomStateMode> = (input: unknown) => RoomStateByMode[M];

export const ROOM_STATE_VALIDATORS = Object.freeze({
    "ballMove": validateGameRoomState,
    "dropInFixture": validateDropInFixtureState,
    "idle": validateIdleRoomState,
    "privateFixture": validatePrivateFixtureState,
} as const satisfies { readonly [M in RoomStateMode]: RoomStateValidator<M> });

export function validateRoomStateForMode<M extends RoomStateMode>(mode: M, input: unknown): RoomStateByMode[M];
export function validateRoomStateForMode(mode: string, input: unknown): RoomState;
export function validateRoomStateForMode(mode: string, input: unknown): RoomState {
    const validator = (ROOM_STATE_VALIDATORS as Readonly<Partial<Record<string, (value: unknown) => RoomState>>>)[mode];
    if (!validator) throw new WireValidationError("STATE_MODE", "mode");
    return validator(input);
}

/** Per-gameplay catalog. contractDigest = sha256(manifest.json + "\0" + state.json + "\0" + wire.ts). */
export const GAMEPLAY_CATALOG = {
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "c8fca655408e3bae34c9b3072681536e03b9258bdc97d827015ccf19feea677e",
    },
    "dropInFixture": {
        id: "dropInFixture",
        constantName: "DropInFixture",
        modeVersion: 1,
        maxPlayers: 8,
        profiles: ["dropIn"],
        stateFragments: [],
        contractDigest: "10a6c06129af42a6f473481239d8a6570a08f2c70e5a5100d511e8e48300badb",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 3,
        maxPlayers: 4,
        profiles: ["default"],
        stateFragments: [],
        contractDigest: "0ecdaaa95a97d83b73df2a3f3d5535f0e4bf113fb50fa64c52a79477f0749ef7",
    },
    "privateFixture": {
        id: "privateFixture",
        constantName: "PrivateFixture",
        modeVersion: 1,
        maxPlayers: 4,
        profiles: ["default", "private"],
        stateFragments: ["ownerReady", "inviteRoom"],
        contractDigest: "93c50eb5f5de997cb09c843bb187b599efdf7111e65228668a958b84cc1597ed",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;
