/** AUTO-GENERATED by apps/server/tools/gameplay-codegen/cli.ts from apps/shared/schema/gameplays/<id>/{manifest.json,state.json}. Do not edit. */
import { WireValidationError } from "../protocol/http";
import { validateGameRoomState, type IGameRoomState } from "./generated/state/ballMove";
import { validateIdleRoomState, type IIdleRoomState } from "./generated/state/idle";

/** Wire root interfaces keyed by canonical gameplay mode id. */
export interface RoomStateByMode {
    "ballMove": IGameRoomState;
    "idle": IIdleRoomState;
}

export type RoomStateMode = keyof RoomStateByMode;
export type RoomState = RoomStateByMode[RoomStateMode];
export type RoomStateValidator<M extends RoomStateMode> = (input: unknown) => RoomStateByMode[M];

export const ROOM_STATE_VALIDATORS = Object.freeze({
    "ballMove": validateGameRoomState,
    "idle": validateIdleRoomState,
} as const satisfies { readonly [M in RoomStateMode]: RoomStateValidator<M> });

export function validateRoomStateForMode<M extends RoomStateMode>(mode: M, input: unknown): RoomStateByMode[M];
export function validateRoomStateForMode(mode: string, input: unknown): RoomState;
export function validateRoomStateForMode(mode: string, input: unknown): RoomState {
    const validator = (ROOM_STATE_VALIDATORS as Readonly<Partial<Record<string, (value: unknown) => RoomState>>>)[mode];
    if (!validator) throw new WireValidationError("STATE_MODE", "mode");
    return validator(input);
}

/** Per-gameplay catalog. contractDigest = sha256(manifest.json + "\0" + state.json). */
export const GAMEPLAY_CATALOG = {
    "ballMove": {
        id: "ballMove",
        constantName: "BallMove",
        modeVersion: 1,
        maxPlayers: 4,
        contractDigest: "b2dbbf2589da1f554fccfcaea0b9e0167f664744c2bca310f7be72705278884b",
    },
    "idle": {
        id: "idle",
        constantName: "Idle",
        modeVersion: 1,
        maxPlayers: 4,
        contractDigest: "ebb621e7aa80ab74098763725f4931a009dba144900a69dccd69bdb2485fce77",
    },
} as const;

export type GameplayCatalogId = keyof typeof GAMEPLAY_CATALOG;
