/** Snake S1 public skin identity catalog. */
// Generated by tools/snake-s1-assets/cli.mjs. DO NOT EDIT.

export const PUBLIC_SNAKE_SKIN_CATALOG_DATA = [
  {
    "skinId": 1,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": true,
    "sortOrder": 1,
    "playerUsable": true,
    "technicalLabel": "皮肤 1"
  },
  {
    "skinId": 2,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 2,
    "playerUsable": true,
    "technicalLabel": "皮肤 2"
  },
  {
    "skinId": 3,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 3,
    "playerUsable": true,
    "technicalLabel": "皮肤 3"
  },
  {
    "skinId": 4,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 4,
    "playerUsable": true,
    "technicalLabel": "皮肤 4"
  },
  {
    "skinId": 10,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 10,
    "playerUsable": true,
    "technicalLabel": "皮肤 10"
  },
  {
    "skinId": 11,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 11,
    "playerUsable": true,
    "technicalLabel": "皮肤 11"
  },
  {
    "skinId": 101,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 101,
    "playerUsable": true,
    "technicalLabel": "皮肤 101"
  },
  {
    "skinId": 111,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 111,
    "playerUsable": true,
    "technicalLabel": "皮肤 111"
  },
  {
    "skinId": 112,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 112,
    "playerUsable": true,
    "technicalLabel": "皮肤 112"
  },
  {
    "skinId": 132,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 132,
    "playerUsable": true,
    "technicalLabel": "皮肤 132"
  },
  {
    "skinId": 133,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 133,
    "playerUsable": true,
    "technicalLabel": "皮肤 133"
  },
  {
    "skinId": 139,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 139,
    "playerUsable": true,
    "technicalLabel": "皮肤 139"
  },
  {
    "skinId": 401,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 401,
    "playerUsable": true,
    "technicalLabel": "皮肤 401"
  },
  {
    "skinId": 403,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 403,
    "playerUsable": true,
    "technicalLabel": "皮肤 403"
  },
  {
    "skinId": 411,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 411,
    "playerUsable": true,
    "technicalLabel": "皮肤 411"
  },
  {
    "skinId": 701,
    "contentVersion": 1,
    "publicationState": "active",
    "isDefault": false,
    "sortOrder": 701,
    "playerUsable": true,
    "technicalLabel": "皮肤 701"
  }
] as const;

export const PUBLIC_SNAKE_SKIN_CATALOG_HASH = "a1cdecbc5e31db3f90ac2fd15465768ef9206b2520000d4ab9f88d6c2135b075";
